using System;
using System.ComponentModel;
using System.Linq;
using System.Windows;
using Core;
using Core.EntityViewModel;
using Core.WindowsManager;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Grid;
using DevExpress.Xpf.LayoutControl;
using Helper;
using KursAM2.Dialogs;
using KursAM2.ViewModel.Logistiks.Warehouse;
using LayoutManager;

namespace KursWPFFormTest
{
    /// <summary>
    ///     Interaction logic for OrderInView.xaml
    /// </summary>
    public partial class OrderInView : ILayout
    {
        private readonly LayoutManagerGridAutoGenerationColumns gridRowsLayout;
        public ComboBoxEdit warehouseTypeComboBoxEdit;

        public OrderInView()
        {
            InitializeComponent();
            LayoutManager = new LayoutManager.LayoutManager(GetType().Name, this, null);
            gridRowsLayout = new LayoutManagerGridAutoGenerationColumns(GetType().Name, gridRows);
            Closing += OrderIn_Closing;
            Loaded += OrderIn_Loaded;
        }

        public LayoutManager.LayoutManager LayoutManager { get; set; }
        public string LayoutManagerName { get; set; }
        public void ResetLayot()
        {
            throw new NotImplementedException();
        }

        private void OrderIn_Loaded(object sender, RoutedEventArgs e)
        {
            LayoutManager.Load();
        }

        private void OrderIn_Closing(object sender, CancelEventArgs e)
        {
            LayoutManager.Save();
            gridRowsLayout.Save();
        }

        private void GridRows_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
            if (LayoutManagerBase.ColumnFieldTypeCheckDecimal(e.Column.FieldType))
                e.Column.EditSettings = new CalcEditSettings
                {
                    DisplayFormat = "n2",
                    Name = e.Column.FieldName + "Calc"
                };
            var ctx = DataContext as OrderInWindowViewModel;
            var doc = ctx?.Document;
            if (doc == null)
                return;
            // ReSharper disable once LocalNameCapturedOnly
            // ReSharper disable once RedundantAssignment
            var inv = new InvoiceProviderRow();
            switch (e.Column.Name)
            {
                case nameof(inv.Unit):
                    e.Column.ReadOnly = true;
                    break;
                case nameof(inv.Nomenkl):
                    var nomenklEdit = new ButtonEditSettings
                    {
                        TextWrapping = TextWrapping.Wrap,
                        IsTextEditable = false
                    };
                    nomenklEdit.DefaultButtonClick += Nomenkl_DefaultButtonClick;
                    e.Column.EditSettings = nomenklEdit;
                    break;
                case nameof(inv.Note):
                    e.Column.EditSettings = new MemoEditSettings
                    {
                        ShowIcon = false
                    };
                    break;
                case nameof(inv.SDRSchet):
                    e.Column.EditSettings = new ComboBoxEditSettings
                    {
                        ItemsSource = MainReferences.SDRSchets.Values,
                        DisplayMember = "Name",
                        ValueMember = "DocCode",
                        AutoComplete = true
                    };
                    break;
            }
        }

        private void GridRows_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            var columnsInfo = gridRowsLayout.Load();
            gridRows.TotalSummary.Clear();
            gridRows.Height = columnsInfo.Height;
            gridRows.Width = columnsInfo.Width;
            foreach (var col in gridRows.Columns) gridRowsLayout.AutoGeneratedColumnSetProperties(columnsInfo.ColumnsInfo, col);
        }

        private void LayoutItems_OnAutoGeneratingItem(object sender, DataLayoutControlAutoGeneratingItemEventArgs e)
        {
            var ctx = DataContext as OrderInWindowViewModel;
            var doc = ctx?.Document;
            if (doc == null)
                return;
            var oldContent = e.Item.Content as BaseEdit;
            if (e.PropertyType == typeof(decimal) || e.PropertyType == typeof(decimal?))
            {
                var newContent = new PopupCalcEdit
                {
                    DisplayFormatString = "n2",
                    MaskUseAsDisplayFormat = true
                };
                BindingHelper.CopyBinding(oldContent, newContent, BaseEdit.EditValueProperty);
                e.Item.Content = newContent;
            }
            switch (e.PropertyName)
            {
                case nameof(doc.DD_IN_NUM):
                    e.Item.IsReadOnly = true;
                    e.Item.Width = 250;
                    break;
                case nameof(doc.DD_EXT_NUM):
                    e.Item.Width = 350;
                    break;
                case nameof(doc.DD_DATE):
                    e.Item.Width = 150;
                    break;
                case nameof(doc.WarehouseSenderType):
                    e.Item.Name = "WarehouseTypeName";
                    warehouseTypeComboBoxEdit = e.Item.Content as ComboBoxEdit;
                    if (doc.Sender != null)
                        if (warehouseTypeComboBoxEdit != null)
                            warehouseTypeComboBoxEdit.IsEnabled = false;
                    e.Item.Width = 300;
                    break;
                case nameof(doc.Sender):
                    var senderEdit = new ButtonEdit
                    {
                        TextWrapping = TextWrapping.Wrap,
                        IsTextEditable = false
                    };
                    senderEdit.DefaultButtonClick += Sender_DefaultButtonClick;
                    BindingHelper.CopyBinding(oldContent, senderEdit, BaseEdit.EditValueProperty);
                    e.Item.Content = senderEdit;
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    e.Item.MinWidth = 600;
                    break;
                case nameof(doc.DD_SCHET):
                    var schetEdit = new ButtonEdit
                    {
                        TextWrapping = TextWrapping.Wrap,
                        IsTextEditable = false
                    };
                    schetEdit.DefaultButtonClick += Schet_DefaultButtonClick;
                    BindingHelper.CopyBinding(oldContent, schetEdit, BaseEdit.EditValueProperty);
                    e.Item.Content = schetEdit;
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    e.Item.MinWidth = 600;
                    break;
                case nameof(doc.WarehouseIn):
                    var wInCB = ViewFluentHelper.SetComboBoxEdit(e.Item, doc.WarehouseIn, "WarehouseIn",
                        MainReferences.Warehouses.Values.ToList().OrderBy(_ => _.Name));
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    e.Item.HorizontalContentAlignment = HorizontalAlignment.Left;
                    wInCB.EditValueChanged += WInCB_EditValueChanged;
                    break;
                case nameof(doc.CREATOR):
                    e.Item.IsReadOnly = true;
                    e.Item.HorizontalAlignment = HorizontalAlignment.Right;
                    break;
                case "State":
                    e.Item.IsReadOnly = true;
                    if (e.Item.Content is ComboBoxEdit cbState) cbState.IsEnabled = false;
                    e.Item.HorizontalAlignment = HorizontalAlignment.Right;
                    break;
                case nameof(doc.Note):
                    ViewFluentHelper.SetDefaultMemoEdit(e.Item);
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    e.Item.MinWidth = 300;
                    break;
            }
            ViewFluentHelper.SetModeUpdateProperties(doc, e.Item, e.PropertyName);
        }
        private void WInCB_EditValueChanged(object sender, EditValueChangedEventArgs e)
        {
            var ctx = DataContext as OrderInWindowViewModel;
            var doc = ctx?.Document;
            if (doc == null)
                return;
            var win = new WindowManager();
            // ReSharper disable once PossibleUnintendedReferenceComparison
            if (doc.WarehouseIn == doc.WarehouseOut)
            {
                win.ShowWinUIMessageBox("Отправитель и получатель не могут совпадать.", "Предупреждение",
                    MessageBoxButton.OK, MessageBoxImage.Warning, MessageBoxResult.OK, MessageBoxOptions.None);
                doc.WarehouseIn = null;
                return;
            }
            doc.Kladovshik = doc.WarehouseIn.Employee;
        }

        private void Schet_DefaultButtonClick(object sender, RoutedEventArgs e)
        {
        }

        private void Sender_DefaultButtonClick(object sender, RoutedEventArgs e)
        {
            var ctx = DataContext as OrderInWindowViewModel;
            var doc = ctx?.Document;
            if (doc == null)
                return;
            switch (ctx.Document?.WarehouseSenderType)
            {
                case WarehouseSenderType.Kontragent:
                    var kontr = StandartDialogs.SelectKontragent();
                    if (kontr == null) return;
                    ctx.Document.KontragentReceiver = kontr;
                    warehouseTypeComboBoxEdit.IsEnabled = false;
                    break;
                case WarehouseSenderType.Store:
                    var warehouse = StandartDialogs.SelectWarehouseDialog();
                    if (warehouse == null) return;
                    ctx.Document.WarehouseOut = warehouse;
                    var win = new WindowManager();
                    // ReSharper disable once PossibleUnintendedReferenceComparison
                    if (doc.WarehouseIn == doc.WarehouseOut)
                    {
                        win.ShowWinUIMessageBox("Отправитель и получатель не могут совпадать.", "Предупреждение",
                            MessageBoxButton.OK, MessageBoxImage.Warning, MessageBoxResult.OK, MessageBoxOptions.None);
                        doc.WarehouseOut = null;
                        return;
                    }
                    warehouseTypeComboBoxEdit.IsEnabled = false;
                    break;
            }
        }

        private void LayoutItems_OnAutoGeneratedUI(object sender, EventArgs e)
        {
            foreach (var item in WindowHelper.GetLogicalChildCollection<MemoEdit>(layoutHeaderItems))
                if (item.EditValue != null && !string.IsNullOrWhiteSpace((string) item.EditValue))
                    item.Height = 80;
        }

        private void Nomenkl_DefaultButtonClick(object sender, RoutedEventArgs e)
        {
            var ctx = DataContext as OrderInWindowViewModel;
            var doc = ctx?.Document;
            if (doc == null)
                return;
            var nomenkls = StandartDialogs.SelectNomenkls();
            if (nomenkls == null || nomenkls.Count <= 0) return;
            ctx.CurrentRow.Nomenkl = nomenkls.First();
        }
    }
}