using System.IO;
using System.Windows;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Grid;
using DevExpress.Xpf.LayoutControl;
using LayoutManager;

namespace KursAM2.View.DialogUserControl
{
    /// <summary>
    ///     Interaction logic for AddNomenklUC.xaml
    /// </summary>
    public partial class AddNomenklFromInvoiceClientUC : ILayout
    {
        readonly MemoryStream defaultLayotNomenklItemGrid = new MemoryStream();
        readonly MemoryStream defaultLayotSelectNomenklItemGrid = new MemoryStream();
        public AddNomenklFromInvoiceClientUC(string layoutName)
        {
            LayoutName = layoutName;
            InitializeComponent();
            LayoutManager = new LayoutManager.LayoutManager(GetType().Name, mainControl);
            LayoutControl = mainControl;
            Loaded += UserControl_Loaded;
            Unloaded += UserControl_Unloaded;
        }

        // ReSharper disable once UnusedAutoPropertyAccessor.Global
        public LayoutControl LayoutControl { get; set; }
        // ReSharper disable once UnusedAutoPropertyAccessor.Global
        public string LayoutName { get; set; }
        public LayoutManager.LayoutManager LayoutManager { get; set; }
        public string LayoutManagerName { get; set; }
        public void ResetLayot()
        {
            defaultLayotNomenklItemGrid.Position = 0;
            defaultLayotSelectNomenklItemGrid.Position = 0;
            NomenklItemGrid.RestoreLayoutFromStream(defaultLayotNomenklItemGrid);
            SelectedNomenklGrid.RestoreLayoutFromStream(defaultLayotSelectNomenklItemGrid);
        }

        private void UserControl_Loaded(object sender, RoutedEventArgs e)
        {
            NomenklItemGrid.SaveLayoutToStream(defaultLayotNomenklItemGrid);
            SelectedNomenklGrid.SaveLayoutToStream(defaultLayotSelectNomenklItemGrid);
            LayoutManager.Load();
        }

        private void UserControl_Unloaded(object sender, RoutedEventArgs e)
        {
            LayoutManager.Save();
        }

        private void NomenklItemGrid_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            foreach (var col in NomenklItemGrid.Columns)
                if (col.FieldType == typeof(decimal) || col.FieldType == typeof(decimal?))
                    col.EditSettings = new CalcEditSettings
                    {
                        AllowDefaultButton = false,
                        DisplayFormat = "n2"
                    };
        }

        private void NomenklItemGrid_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
            //e.Column.ReadOnly = true;
        }

        private void SelectedNomenklGrid_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
            //e.Column.ReadOnly = true;
        }

        private void SelectedNomenklGrid_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            foreach (var col in SelectedNomenklGrid.Columns)
                if (col.FieldType == typeof(decimal) || col.FieldType == typeof(decimal?))
                    col.EditSettings = new CalcEditSettings
                    {
                        AllowDefaultButton = false,
                        DisplayFormat = "n2"
                    };
        }
    }
}