using System.Windows;
using Core.ViewModel.Base;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Grid;

namespace KursAM2.View.DialogUserControl
{
    /// <summary>
    ///     Interaction logic for DefaultTableSelectUC.xaml
    /// </summary>
    public partial class DefaultTableSelectUC
    {
        public DefaultTableSelectUC()
        {
            InitializeComponent();
        }

        private void GridControlSearch_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
            e.Column.ReadOnly = e.Column.FieldName != "IsSelected";
        }

        private void GridControlSearch_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            foreach (var c in gridControlSearch.Columns)
                if (c.EditSettings == null)
                {c.EditSettings = new TextEditSettings
                    {
                        SelectAllOnMouseUp = true
                    };
                }

            foreach (var col in gridControlSearch.Columns)
                if (col.FieldType == typeof(decimal) || col.FieldType == typeof(decimal?))
                    col.EditSettings = new CalcEditSettings
                    {
                        AllowDefaultButton = false,
                        DisplayFormat = "n2"
                    };
        }

        private void GridViewDocument_OnRowDoubleClick(object sender, RowDoubleClickEventArgs e)
        {
            if (!(DataContext is RSWindowViewModelBase ctx)) return;
            ctx.DialogResult = true;
            ctx.Form?.Close();
        }
    }
}