using System.Windows;
using Core.ViewModel.Base;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Grid;

namespace KursAM2.View.DialogUserControl
{
    /// <summary>
    ///     Interaction logic for KontragentSelectDialogUC.xaml
    /// </summary>
    public partial class KontragentSelectDialogUC : IDataUserControl
    {
        public KontragentSelectDialogUC()
        {
            InitializeComponent();
            //ApplicationThemeHelper.ApplicationThemeName = Theme.MetropolisLightName;
            //LayoutManager = new LayoutManager.LayoutManager(GlobalOptions.KursSystem(),GetType().Name, gridControlSearch);
            //LayoutControl = gridControlSearch;
            //Loaded += KontragentSelectDialogUC_Loaded;
            //Unloaded += KontragentSelectDialogUC_Unloaded;
        }

        // public LayoutManagerBase LayoutManager { get; set; }
        public DependencyObject LayoutControl { get; }

        //private void KontragentSelectDialogUC_Unloaded(object sender, RoutedEventArgs e)
        //{
        //    LayoutManager.Save();
        //}

        //private void KontragentSelectDialogUC_Loaded(object sender, RoutedEventArgs e)
        //{
        //    LayoutManager.Load();
        //}

        private void GridControlSearch_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
            e.Column.ReadOnly = true;
            e.Column.Visible = e.Column.Name switch
            {
                "Name" => true,
                "FullName" => true,
                "StartBalans" => true,
                "ResponsibleEmployee" => true,
                "Currency" => true,
                "ISBalans" => true,
                _ => false
            };
        }

        private void GridControlSearch_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            foreach (var c in gridControlSearch.Columns)
                if (c.EditSettings == null)
                    c.EditSettings = new TextEditSettings
                    {
                        SelectAllOnMouseUp = true
                    };
            foreach (var col in gridControlSearch.Columns)
                if (col.FieldType == typeof(decimal) || col.FieldType == typeof(decimal?))
                    col.EditSettings = new CalcEditSettings
                    {
                        AllowDefaultButton = false,
                        DisplayFormat = "n2"
                    };
        }

        private void gridViewDocument_RowDoubleClick(object sender, RowDoubleClickEventArgs e)
        {
            if (!(DataContext is KontragentSelectDialog ctx)) return;
            ctx.DialogResult = true;
            ctx.Form?.Close();
        }

        private void ButtonEdit_EditValueChanging(object sender, EditValueChangingEventArgs e)
        {
            if (string.IsNullOrEmpty((string)e.NewValue))
            {
                if (!(DataContext is KontragentSelectDialog ctx)) return;
                ctx.SearchClear(null);
            }
        }
    }
}
