using System.ComponentModel;
using System.Windows;
using System.Windows.Controls;
using Core.Menu;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Grid;
using Helper;
using LayoutManager;

namespace KursAM2.View.Base
{
    /// <summary>
    ///     Interaction logic for KursBaseWindow.xaml
    /// </summary>
    public partial class KursBaseSearchWindow : ILayout
    {
        public KursBaseSearchWindow()
        {
            InitializeComponent();
            Loaded += KursBaseWindow_Loaded;
            Closing += KursBaseWindow_Closing;
        }

        public LayoutManager.LayoutManager LayoutManager { get; set; }
        public string LayoutManagerName { get; set; }

        private void KursBaseWindow_Closing(object sender, CancelEventArgs e)
        {
            LayoutManager.Save();
        }

        private void KursBaseWindow_Loaded(object sender, RoutedEventArgs e)
        {
            LayoutManager = new LayoutManager.LayoutManager(LayoutManagerName, this, resultGridControl);
            LayoutManager.Load();
        }

        private void MenuButton_OnClick(object sender, RoutedEventArgs e)
        {
            var menu = sender as Button;
            if (!(menu?.DataContext is MenuButtonInfo d) || d.SubMenu.Count == 0) return;
            d.MenuOpen(this);
        }

        private void KursBaseSearchWindow_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
        }

        private void KursBaseSearchWindow_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
            if (KursGridControlHelper.ColumnFieldTypeCheckDecimal(e.Column.FieldType))
                e.Column.EditSettings = new CalcEditSettings
                {
                    DisplayFormat = "n2",
                    Name = e.Column.FieldName + "Calc"
                };
        }
    }
}