using System.ComponentModel;
using System.Windows;
using DevExpress.Data;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Grid;
using Helper;
using KursAM2.ViewModel.Reference;
using LayoutManager;

namespace KursAM2.View.Base
{
    /// <summary>
    ///     Interaction logic for GridFormBaseView.xaml
    /// </summary>
    public partial class TreeListFormBaseView : ILayout
    {
        public TreeListFormBaseView()
        {
            InitializeComponent();
            Loaded += TreeListFormBaseView_Loaded;
            Closing += TreeListFormBaseView_Closing;
        }

        public LayoutManager.LayoutManager LayoutManager { get; set; }
        public string LayoutManagerName { get; set; }
        public void ResetLayot()
        {
            throw new System.NotImplementedException();
        }

        private void TreeListFormBaseView_Closing(object sender, CancelEventArgs e)
        {
            LayoutManager.Save();
        }

        private void TreeListFormBaseView_Loaded(object sender, RoutedEventArgs e)
        {
            if (LayoutManager == null)
                LayoutManager = new LayoutManager.LayoutManager(GetType().Name + "." + (LayoutManagerName ?? "base"),
                    this, gridDocuments);
            LayoutManager.Load();
        }

        private void GridDocuments_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
            var seteditor = DataContext as ILayoutFluentSetEditors;
            seteditor?.SetTreeListColumn((TreeListColumn)e.Column);
        }

        private void GridDocuments_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            gridDocuments.TotalSummary.Clear();
            foreach (var col in gridDocuments.Columns)
                if (col.FieldType == typeof(decimal) || col.FieldType == typeof(decimal?))
                {
                    col.EditSettings = new CalcEditSettings
                    {
                        AllowDefaultButton = false,
                        DisplayFormat = "n2"
                    };
                    var summary = new TreeListSummaryItem
                    {
                        SummaryType = SummaryItemType.Sum,
                        ShowInColumn = col.FieldName,
                        DisplayFormat = "{0:n2}",
                        FieldName = col.FieldName
                    };
                    gridDocuments.TotalSummary.Add(summary);
                }
        }
    }
}