using System;
using System.ComponentModel.DataAnnotations;
using Core.Finance;
using DevExpress.Mvvm.DataAnnotations;
using KursAM2.ViewModel.Management.ManagementBalans;

namespace KursAM2.ViewModel.Finance
{
    [MetadataType(typeof(DataAnnotationsMoneyInPathItem))]
    public class MoneyInPathItem : SummaCompareCurrencies
    {
        public DocumentTypes DocumentType { set; get; }
        public string KontragentFromName { set; get; }
        public DateTime Date { set; get; }
        public string DocumentNum { set; get; }
        public string KontragentName { set; get; }
        public string KontragentType { set; get; }
    }

    public static class DataAnnotationsMoneyInPathItem
    {
        public static void BuildMetadata(MetadataBuilder<MoneyInPathItem> builder)
        {
            builder.Property(_ => _.ParentId).NotAutoGenerated();
            builder.Property(_ => _.DocCode).NotAutoGenerated();
            builder.Property(_ => _.Id).NotAutoGenerated();
            builder.Property(_ => _.Parent).NotAutoGenerated();
            builder.Property(_ => _.ParentDC).NotAutoGenerated();
            builder.Property(_ => _.ParentDC).NotAutoGenerated();
            builder.Property(_ => _.State).NotAutoGenerated();
            builder.Property(_ => _.StringId).NotAutoGenerated();
            builder.Property(_ => _.IsDifferent).NotAutoGenerated();
            builder.Property(_ => _.Name).NotAutoGenerated();
            builder.Property(_ => _.DocumentType).DisplayName("Тип документа").Description("Тип документа").ReadOnly();
            builder.Property(_ => _.DocumentNum).DisplayName("№").Description("№ документа").ReadOnly();
            builder.Property(_ => _.Date).DisplayName("Дата").Description("Дата документа").ReadOnly();
            builder.Property(_ => _.Currency).DisplayName("Валюта").Description("Валюта операции").ReadOnly();
            builder.Property(_ => _.KontragentName).ReadOnly().DisplayName("Контрагент").Description("");
            builder.Property(_ => _.KontragentType).ReadOnly().DisplayName("Тип контрагента").Description("");
            builder.Property(_ => _.Summa).ReadOnly().DisplayName("Сумма").Description("Сумма операции");
            builder.Property(_ => _.Note).DisplayName("Примечание").Description("").ReadOnly();
            builder.Group("Контрагент")
                .ContainsProperty(_ => _.KontragentName)
                .ContainsProperty(_ => _.Note)
                .ContainsProperty(_ => _.Currency)
                .ContainsProperty(_ => _.Summa);
            builder.Property(_ => _.SummaRUB).ReadOnly().DisplayName("На начало").Description("").NumericMask("n2");
            builder.Property(_ => _.SummaRUB2)
                .DisplayName("На конец")
                .Description("На конец RUB")
                .ReadOnly()
                .NumericMask("n2");
            builder.Property(_ => _.DeltaRUB)
                .DisplayName("Результат")
                .Description("Результат")
                .ReadOnly()
                .NumericMask("n2");
            builder.Group("RUB")
                .ContainsProperty(_ => _.SummaRUB)
                .ContainsProperty(_ => _.SummaRUB2)
                .ContainsProperty(_ => _.DeltaRUB);
            builder.Property(_ => _.SummaUSD).ReadOnly().DisplayName("На начало").Description("").NumericMask("n2");
            builder.Property(_ => _.SummaUSD2)
                .DisplayName("На конец")
                .Description("На конец USD")
                .ReadOnly()
                .NumericMask("n2");
            builder.Property(_ => _.DeltaUSD)
                .DisplayName("Результат")
                .Description("Результат")
                .ReadOnly()
                .NumericMask("n2");
            builder.Group("USD")
                .ContainsProperty(_ => _.SummaUSD)
                .ContainsProperty(_ => _.SummaUSD2)
                .ContainsProperty(_ => _.DeltaUSD);
            builder.Property(_ => _.SummaEUR).ReadOnly().DisplayName("На начало").Description("").NumericMask("n2");
            builder.Property(_ => _.SummaEUR2)
                .DisplayName("На конец")
                .Description("На конец EUR")
                .ReadOnly()
                .NumericMask("n2");
            builder.Property(_ => _.DeltaEUR)
                .DisplayName("Результат")
                .Description("Результат")
                .ReadOnly()
                .NumericMask("n2");
            builder.Group("EUR")
                .ContainsProperty(_ => _.SummaEUR)
                .ContainsProperty(_ => _.SummaEUR2)
                .ContainsProperty(_ => _.DeltaEUR);
            builder.Property(_ => _.SummaGBP).ReadOnly().DisplayName("На начало").Description("").NumericMask("n2");
            builder.Property(_ => _.SummaGBP2)
                .DisplayName("На конец")
                .Description("На конец GBP")
                .ReadOnly()
                .NumericMask("n2");
            builder.Property(_ => _.DeltaGBP)
                .DisplayName("Результат")
                .Description("Результат")
                .ReadOnly()
                .NumericMask("n2");
            builder.Group("GBP")
                .ContainsProperty(_ => _.SummaGBP)
                .ContainsProperty(_ => _.SummaGBP2)
                .ContainsProperty(_ => _.DeltaGBP);
            builder.Property(_ => _.SummaCHF).ReadOnly().DisplayName("На начало").Description("").NumericMask("n2");
            builder.Property(_ => _.SummaCHF2)
                .DisplayName("На конец")
                .Description("На конец CHF")
                .ReadOnly()
                .NumericMask("n2");
            builder.Property(_ => _.DeltaCHF)
                .DisplayName("Результат")
                .Description("Результат")
                .ReadOnly()
                .NumericMask("n2");
            builder.Group("CHF")
                .ContainsProperty(_ => _.SummaCHF)
                .ContainsProperty(_ => _.SummaCHF2)
                .ContainsProperty(_ => _.DeltaCHF);
            builder.Property(_ => _.SummaSEK).ReadOnly().DisplayName("На начало").Description("").NumericMask("n2");
            builder.Property(_ => _.SummaSEK2)
                .DisplayName("На конец")
                .Description("На конец SEK")
                .ReadOnly()
                .NumericMask("n2");
            builder.Property(_ => _.DeltaSEK)
                .DisplayName("Результат")
                .Description("Результат")
                .ReadOnly()
                .NumericMask("n2");
            builder.Group("SEK")
                .ContainsProperty(_ => _.SummaSEK)
                .ContainsProperty(_ => _.SummaSEK2)
                .ContainsProperty(_ => _.DeltaSEK);
        }
    }
}