using System;
using System.ComponentModel;
using System.Linq;
using System.Windows;
using Core;
using Core.WindowsManager;
using DevExpress.Data;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Grid;
using DevExpress.Xpf.LayoutControl;
using Helper;
using KursAM2.ViewModel.Logistiks.Warehouse;
using LayoutManager;

namespace KursAM2.View.Logistiks.Warehouse
{
    /// <summary>
    ///     Interaction logic for OrderInView.xaml
    /// </summary>
    public partial class OrderOutView : ILayout
    {
        public OrderOutView()
        {
            InitializeComponent();
            Closing += OrderIn_Closing;
            Loaded += OrderIn_Loaded;
        }

        public LayoutManager.LayoutManager LayoutManager { get; set; }
        public string LayoutManagerName { get; set; }
        public void SaveLayout()
        {
            LayoutManager.Save();
        }

        private void OrderIn_Loaded(object sender, RoutedEventArgs e)
        {
            LayoutManager?.Load();
        }

        private void OrderIn_Closing(object sender, CancelEventArgs e)
        {
            LayoutManager.Save();
        }

        private void GridRows_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
            if (KursGridControlHelper.ColumnFieldTypeCheckDecimal(e.Column.FieldType))
                e.Column.EditSettings = new CalcEditSettings
                {
                    DisplayFormat = "n2",
                    Name = e.Column.FieldName + "Calc"
                };
            var ctx = DataContext as OrderOutWindowViewModel;
            var doc = ctx?.Document;
            if (doc == null)
                // ReSharper disable once RedundantJumpStatement
                return;
            switch (e.Column.Name)
            {
                case "SDRSchet":
                    e.Column.EditSettings = new ComboBoxEditSettings
                    {
                        ItemsSource = MainReferences.SDRSchets.Values,
                        DisplayMember = "Name",
                        AutoComplete = true
                    };
                    break;
            }
        }

        private void GridRows_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            if (gridRows.Bands != null && gridRows.Bands.Count > 0)
            {
                var bandid = 1;
                foreach (var b in gridRows.Bands)
                {
                    b.Name = "band" + bandid;
                    bandid++;
                }
            }

            gridRows.TotalSummary.Clear();
            foreach (var col in gridRows.Columns)
                if (KursGridControlHelper.ColumnFieldTypeCheckDecimal(col.FieldType))
                {
                    var summary = new GridSummaryItem
                    {
                        SummaryType = SummaryItemType.Sum,
                        ShowInColumn = col.FieldName,
                        DisplayFormat = "{0:n2}",
                        FieldName = col.FieldName
                    };
                    gridRows.TotalSummary.Add(summary);
                }

            LayoutManager = new LayoutManager.LayoutManager(GetType().Name, this, gridRows);
        }

        private void LayoutItems_OnAutoGeneratingItem(object sender, DataLayoutControlAutoGeneratingItemEventArgs e)
        {
            var ctx = DataContext as OrderOutWindowViewModel;
            var doc = ctx?.Document;
            if (doc == null)
                return;
            var oldContent = e.Item.Content as BaseEdit;
            if (e.PropertyType == typeof(decimal) || e.PropertyType == typeof(decimal?))
            {
                var newContent = new PopupCalcEdit
                {
                    DisplayFormatString = "n2",
                    MaskUseAsDisplayFormat = true
                };
                BindingHelper.CopyBinding(oldContent, newContent, BaseEdit.EditValueProperty);
                e.Item.Content = newContent;
            }

            switch (e.PropertyName)
            {
                case nameof(doc.DD_IN_NUM):
                    e.Item.IsReadOnly = true;
                    e.Item.Width = 250;
                    break;
                case nameof(doc.DD_EXT_NUM):
                    e.Item.Width = 350;
                    break;
                case nameof(doc.DD_DATE):
                    e.Item.Width = 150;
                    break;

                case nameof(doc.DD_SCHET):
                    var schetEdit = new ButtonEdit
                    {
                        TextWrapping = TextWrapping.Wrap,
                        IsTextEditable = false
                    };
                    //schetEdit.DefaultButtonClick += Schet_DefaultButtonClick;
                    BindingHelper.CopyBinding(oldContent, schetEdit, BaseEdit.EditValueProperty);
                    e.Item.Content = schetEdit;
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    e.Item.MinWidth = 600;
                    break;
                case nameof(doc.WarehouseIn):
                    var wInCB = ViewFluentHelper.SetComboBoxEdit(e.Item, doc.WarehouseIn, "WarehouseIn",
                        MainReferences.Warehouses.Values.ToList().OrderBy(_ => _.Name));
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    e.Item.HorizontalContentAlignment = HorizontalAlignment.Left;
                    wInCB.EditValueChanged += WInCB_EditValueChanged;
                    break;
                case nameof(doc.WarehouseOut):
                    var wOutCB = ViewFluentHelper.SetComboBoxEdit(e.Item, doc.WarehouseOut, "WarehouseOut",
                        MainReferences.Warehouses.Values.ToList().OrderBy(_ => _.Name));
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    e.Item.HorizontalContentAlignment = HorizontalAlignment.Left;
                    wOutCB.EditValueChanged += WOutCB_EditValueChanged;
                    break;
                case nameof(doc.CREATOR):
                    e.Item.IsReadOnly = true;
                    e.Item.HorizontalAlignment = HorizontalAlignment.Right;
                    break;
                case "State":
                    e.Item.IsReadOnly = true;
                    if (e.Item.Content is ComboBoxEdit cbState) cbState.IsEnabled = false;
                    e.Item.HorizontalAlignment = HorizontalAlignment.Right;
                    break;
                case nameof(doc.Note):
                    ViewFluentHelper.SetDefaultMemoEdit(e.Item);
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    e.Item.MinWidth = 300;
                    break;
            }

            ViewFluentHelper.SetModeUpdateProperties(doc, e.Item, e.PropertyName);
        }

        private void WOutCB_EditValueChanged(object sender, EditValueChangedEventArgs e)
        {
            var ctx = DataContext as OrderOutWindowViewModel;
            var doc = ctx?.Document;
            if (doc == null)
                return;
            var win = new WindowManager();
            // ReSharper disable once PossibleUnintendedReferenceComparison
            if (doc.WarehouseIn == doc.WarehouseOut)
            {
                win.ShowWinUIMessageBox("Отправитель и получатель не могут совпадать.", "Предупреждение",
                    MessageBoxButton.OK, MessageBoxImage.Warning, MessageBoxResult.OK, MessageBoxOptions.None);
                doc.WarehouseOut = null;
                return;
            }

            doc.Kladovshik = doc.WarehouseOut.Employee;
        }

        private void WInCB_EditValueChanged(object sender, EditValueChangedEventArgs e)
        {
            var ctx = DataContext as OrderOutWindowViewModel;
            var doc = ctx?.Document;
            if (doc == null)
                return;
            var win = new WindowManager();
            // ReSharper disable once PossibleUnintendedReferenceComparison
            if (doc.WarehouseIn == doc.WarehouseOut)
            {
                win.ShowWinUIMessageBox("Отправитель и получатель не могут совпадать.", "Предупреждение",
                    MessageBoxButton.OK, MessageBoxImage.Warning, MessageBoxResult.OK, MessageBoxOptions.None);
                doc.WarehouseIn = null;
            }
        }

        private void LayoutItems_OnAutoGeneratedUI(object sender, EventArgs e)
        {
        }

        private void TableViewRows_OnCellValueChanged(object sender, CellValueChangedEventArgs e)
        {
            var dtx = DataContext as OrderOutWindowViewModel;
            if (dtx == null) return;
            if (e.Column.FieldName == "Quantity")
                if (dtx.CurrentRow.Quantity > dtx.CurrentRow.MaxQuantity)
                {
                    WindowManager.ShowMessage("Кол-во отгрузки первышает кол-ва на складе",
                        "Ошибка", MessageBoxImage.Stop);
                    dtx.CurrentRow.Quantity = (decimal) e.OldValue;
                }
        }
    }
}