using System;
using System.Linq;
using System.Windows;
using System.Windows.Media;
using Core.WindowsManager;
using DevExpress.Data;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Grid;
using DevExpress.Xpf.LayoutControl;
using Helper;
using KursAM2.ViewModel.Logistiks.Warehouse;
using KursDomain;
using KursDomain.ICommon;
using KursDomain.References;
using LayoutManager;
using ItemsSourceChangedEventArgs = DevExpress.Xpf.Grid.ItemsSourceChangedEventArgs;

namespace KursAM2.View.Logistiks.Warehouse
{
    /// <summary>
    ///     Interaction logic for OrderInView.xaml
    /// </summary>
    public partial class OrderOutView2 : ILayout
    {
        public ComboBoxEdit comboWarehouseIn;
        public ComboBoxEdit comboWarehouseOut;
        public DateEdit docDateEditor;

        public OrderOutView2()
        {
            InitializeComponent();
        }

        public LayoutManager.LayoutManager LayoutManager { get; set; }
        public string LayoutManagerName { get; set; }

        public void SaveLayout()
        {
            LayoutManager.Save();
        }

        private void GridRows_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
            if (KursGridControlHelper.ColumnFieldTypeCheckDecimal(e.Column.FieldType))
                e.Column.EditSettings = new CalcEditSettings
                {
                    DisplayFormat = "n2",
                    Name = e.Column.FieldName + "Calc"
                };
            var ctx = DataContext as OrderOutWindowViewModel2;
            var doc = ctx?.Document;
            if (doc == null)
                // ReSharper disable once RedundantJumpStatement
                return;
            switch (e.Column.Name)
            {
                case "SHPZ":
                    //e.Column.EditSettings = new ComboBoxEditSettings
                    //{
                    //    ItemsSource = GlobalOptions.ReferencesCache.GetSDRSchetAll().Cast<SDRSchet>()
                    //        .OrderBy(_ => _.Name).ToList(),
                    //    DisplayMember = "Name",
                    //    AutoComplete = true,
                    //};

                    e.Column.EditSettings = new ComboBoxEditSettings
                    {
                        AllowDefaultButton = false,
                        ItemsSource = GlobalOptions.ReferencesCache.GetSDRSchetAll().Cast<SDRSchet>()
                            .OrderBy(_ => _.Name).ToList(),
                        DisplayMember = "Name",
                        AutoComplete = true,
                        Buttons = { new ButtonInfo()
                        {
                            GlyphKind = GlyphKind.Down
                        }, {  new ButtonInfo()
                        {
                            GlyphKind = GlyphKind.Cancel
                        } } }
                    };
                    break;
            }
        }

        private void GridRows_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            if (gridRows.Bands != null && gridRows.Bands.Count > 0)
            {
                var bandid = 1;
                foreach (var b in gridRows.Bands)
                {
                    b.Name = "band" + bandid;
                    bandid++;
                }
            }

            gridRows.TotalSummary.Clear();
            foreach (var col in gridRows.Columns)
                if (KursGridControlHelper.ColumnFieldTypeCheckDecimal(col.FieldType))
                {
                    var summary = new GridSummaryItem
                    {
                        SummaryType = SummaryItemType.Sum,
                        ShowInColumn = col.FieldName,
                        DisplayFormat = "{0:n2}",
                        FieldName = col.FieldName
                    };
                    gridRows.TotalSummary.Add(summary);
                }

            LayoutManager = new LayoutManager.LayoutManager(GlobalOptions.KursSystem(), GetType().Name, this, gridRows);
        }

        private void LayoutItems_OnAutoGeneratingItem(object sender, DataLayoutControlAutoGeneratingItemEventArgs e)
        {
            try
            {
                var ctx = DataContext as OrderOutWindowViewModel2;
                var doc = ctx?.Document;
                if (doc == null)
                    return;
                var oldContent = e.Item.Content as BaseEdit;
                if (e.PropertyType == typeof(decimal) || e.PropertyType == typeof(decimal?))
                {
                    var newContent = new PopupCalcEdit
                    {
                        DisplayFormatString = "n2",
                        MaskUseAsDisplayFormat = true
                    };
                    BindingHelper.CopyBinding(oldContent, newContent, BaseEdit.EditValueProperty);
                    e.Item.Content = newContent;
                }

                switch (e.PropertyName)
                {
                    case nameof(doc.DocNum):
                        e.Item.IsReadOnly = true;
                        e.Item.Width = 240;
                        break;
                    case nameof(doc.DocExtNum):
                        e.Item.Width = 350;
                        break;
                    case nameof(doc.DocDate):
                        e.Item.Width = 158;
                        e.Item.Margin = new Thickness(10, 0, 0, 0);
                        docDateEditor = e.Item.Content as DateEdit;
                        break;
                    case nameof(doc.WarehouseIn):
                        comboWarehouseIn = ViewFluentHelper.SetComboBoxEdit(e.Item, doc.WarehouseIn, "WarehouseIn",
                            GlobalOptions.ReferencesCache.GetWarehousesAll().Cast<KursDomain.References.Warehouse>()
                                .OrderBy(_ => _.Name).ToList());
                        e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                        e.Item.HorizontalContentAlignment = HorizontalAlignment.Left;
                        comboWarehouseIn.EditValueChanged += WInCB_EditValueChanged;
                        break;
                    case nameof(doc.WarehouseOut):
                        comboWarehouseOut = ViewFluentHelper.SetComboBoxEdit(e.Item, doc.WarehouseOut, "WarehouseOut",
                            GlobalOptions.ReferencesCache.GetWarehousesAll().Cast<KursDomain.References.Warehouse>()
                                .OrderBy(_ => _.Name).ToList());
                        e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                        e.Item.HorizontalContentAlignment = HorizontalAlignment.Left;
                        comboWarehouseOut.EditValueChanged += WOutCB_EditValueChanged;
                        break;
                    case nameof(doc.Creator):
                        e.Item.IsReadOnly = true;
                        e.Item.HorizontalAlignment = HorizontalAlignment.Right;
                        e.Item.Width = 200;
                        break;
                    case nameof(doc.State):
                        e.Item.IsReadOnly = true;
                        e.Item.Width = 200;
                        e.Item.Margin = new Thickness(10, 0, 0, 0);
                        e.Item.Visibility = Visibility.Visible;
                        if (e.Item.Content is ComboBoxEdit cbState)
                        {
                            cbState.AllowDefaultButton = false;
                            cbState.PopupOpened += OrderOutView2_PopupOpened;
                            //cbState.FontWeight = FontWeights.Bold;
                            cbState.EditValueChanged += OrderOutView2_EditValueChanged;
                        }

                        e.Item.HorizontalAlignment = HorizontalAlignment.Right;
                        break;
                    /*
                    case nameof(doc.Note):
                        if (e.Item.Content is TextEdit ted)
                        {
                            ted.TextWrapping = TextWrapping.Wrap;
                            ted.AcceptsReturn = true;
                            ted.AcceptsTab = true;
                            ted.Width = 600;
                            //ted.HorizontalAlignment = HorizontalAlignment.Left;
                            //ted.HorizontalContentAlignment = HorizontalAlignment.Left;
                        }
                        e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                        e.Item.HorizontalContentAlignment = HorizontalAlignment.Left;
                        //e.Item.Width = 600;
                        break;
                */
                }

                ViewFluentHelper.SetModeUpdateProperties(doc, e.Item, e.PropertyName);
            }
            catch (Exception ex)
            {
                WindowManager.ShowError(ex);
            }
        }

        private void OrderOutView2_EditValueChanged(object sender, EditValueChangedEventArgs e)
        {
            switch ((RowStatus)e.NewValue)
            {
                case RowStatus.NewRow:
                    ((ComboBoxEdit)sender).Foreground = Brushes.Red;
                    break;
                case RowStatus.NotEdited:
                    ((ComboBoxEdit)sender).Foreground = Brushes.Green;
                    break;
                case RowStatus.Edited:
                    ((ComboBoxEdit)sender).Foreground = Brushes.Blue;
                    break;
                default:
                    ((ComboBoxEdit)sender).Foreground = Brushes.Black;
                    break;
            }
        }

        private void OrderOutView2_PopupOpened(object sender, RoutedEventArgs e)
        {
            ((ComboBoxEdit)sender).IsPopupOpen = false;
        }

        private void WOutCB_EditValueChanged(object sender, EditValueChangedEventArgs e)
        {
            var ctx = DataContext as OrderOutWindowViewModel2;
            var doc = ctx?.Document;
            if (doc == null)
                return;
            var win = new WindowManager();
            // ReSharper disable once PossibleUnintendedReferenceComparison
            if (doc.WarehouseIn == doc.WarehouseOut)
            {
                win.ShowWinUIMessageBox("Отправитель и получатель не могут совпадать.", "Предупреждение",
                    MessageBoxButton.OK, MessageBoxImage.Warning, MessageBoxResult.OK, MessageBoxOptions.None);
                doc.WarehouseOut = null;
            }

            doc.Model.DD_KLADOV_TN =
                doc.WarehouseOut?.StoreKeeper?.TabelNumber;
            doc.RaisePropertyChanged(nameof(doc.StoreKeeper));
        }

        private void WInCB_EditValueChanged(object sender, EditValueChangedEventArgs e)
        {
            var ctx = DataContext as OrderOutWindowViewModel2;
            var doc = ctx?.Document;
            if (doc == null)
                return;
            var win = new WindowManager();
            // ReSharper disable once PossibleUnintendedReferenceComparison
            if (doc.WarehouseIn == doc.WarehouseOut)
            {
                win.ShowWinUIMessageBox("Отправитель и получатель не могут совпадать.", "Предупреждение",
                    MessageBoxButton.OK, MessageBoxImage.Warning, MessageBoxResult.OK, MessageBoxOptions.None);
                doc.WarehouseIn = null;
            }
        }

        private void LayoutItems_OnAutoGeneratedUI(object sender, EventArgs e)
        {
        }

        
        private void gridRows_ItemsSourceChanged(object sender, ItemsSourceChangedEventArgs e)
        {
        }
    }
}
