using System.ComponentModel;
using System.Windows;
using DevExpress.Data;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Grid;
using Helper;
using LayoutManager;

namespace KursAM2.View.Logistiks.Warehouse
{
    /// <summary>
    ///     Interaction logic for WarehouseOrderSearchView.xaml
    /// </summary>
    public partial class WarehouseOrderSearchView : ILayout
    {
        public WarehouseOrderSearchView(string layoutname)
        {
            LayoutManagerName = layoutname;
            InitializeComponent();
            Loaded += SearchBaseView_Loaded;
            Closing += SearchBaseView_Closing;
        }

        public LayoutManager.LayoutManager LayoutManager { get; set; }
        public string LayoutManagerName { get; set; }
        public void SaveLayout()
        {
            LayoutManager.Save();
        }

        private void SearchBaseView_Closing(object sender, CancelEventArgs e)
        {
            LayoutManager.Save();
        }

        private void SearchBaseView_Loaded(object sender, RoutedEventArgs e)
        {
            LayoutManager.Load();
        }

        private void ResultGridControl_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
            e.Column.ReadOnly = true;
            if (KursGridControlHelper.ColumnFieldTypeCheckDecimal(e.Column.FieldType))
                e.Column.EditSettings = new CalcEditSettings
                {
                    DisplayFormat = "n2",
                    Name = e.Column.FieldName + "Calc",
                    AllowDefaultButton = false
                };
        }

        private void ResultGridControl_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            if (resultGridControl.Bands != null && resultGridControl.Bands.Count > 0)
            {
                var bandid = 1;
                foreach (var b in resultGridControl.Bands)
                {
                    b.Name = "band" + bandid;
                    bandid++;
                }
            }

            resultGridControl.TotalSummary.Clear();
            foreach (var col in resultGridControl.Columns)
                if (KursGridControlHelper.ColumnFieldTypeCheckDecimal(col.FieldType))
                {
                    var summary = new GridSummaryItem
                    {
                        SummaryType = SummaryItemType.Sum,
                        ShowInColumn = col.FieldName,
                        DisplayFormat = "{0:n2}",
                        FieldName = col.FieldName
                    };
                    resultGridControl.TotalSummary.Add(summary);
                }

            LayoutManager = new LayoutManager.LayoutManager(LayoutManagerName, this, resultGridControl);
        }
    }
}