using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Windows;
using Core.EntityViewModel;
using DevExpress.Data;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Grid;
using KursAM2.ViewModel.Logistiks.Warehouse;
using LayoutManager;

namespace KursAM2.View.Logistiks.Warehouse
{
    /// <summary>
    ///     Расходная накладная для клиентов
    /// </summary>
    public partial class WaybillView : ILayout
    {
        public WaybillView()
        {
            InitializeComponent();
            Loaded += WaybillClientView_Loaded;
            Closing += WaybillClientView_Closing;
        }

        public LayoutManager.LayoutManager LayoutManager { get; set; }
        public string LayoutManagerName { get; set; }

        private void WaybillClientView_Closing(object sender, CancelEventArgs e)
        {
           LayoutManager.Save();
        }

        private void WaybillClientView_Loaded(object sender, RoutedEventArgs e)
        {
            LayoutManager = new LayoutManager.LayoutManager(GetType().Name, this, mainLayoutControl);
            LayoutManager.Load();
        }

        private void otvetsCombobox_ProcessNewValue(DependencyObject sender, ProcessNewValueEventArgs e)
        {
            if (e.DisplayText != string.Empty)
            {
                ((List<string>) otvetsCombobox.ItemsSource).Add(e.DisplayText);
                e.Handled = true;
            }
        }

        private void gridRows_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
            if (LayoutManagerBase.ColumnFieldTypeCheckDecimal(e.Column.FieldType))
                e.Column.EditSettings = new CalcEditSettings
                {
                    DisplayFormat = "n2",
                    Name = e.Column.FieldName + "Calc"
                };
            var ctx = DataContext as WaybillWindowViewModel;
            var doc = ctx?.Document;
            if (doc == null)
                return;
            // ReSharper disable once LocalNameCapturedOnly
            // ReSharper disable once RedundantAssignment
            var row = new WaybillRow();
            switch (e.Column.Name)
            {
                case nameof(row.IsUsluga):
                    break;
            }
        }

        private void gridRows_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            gridRows.TotalSummary.Clear();
            foreach (var col in gridRows.Columns)
            {
                if (col.FieldType == typeof(decimal) || col.FieldType == typeof(decimal?))
                {
                    col.EditSettings = new CalcEditSettings
                    {
                        AllowDefaultButton = true,
                        DisplayFormat = "n2"
                    };
                    var summary = new GridSummaryItem
                    {
                        SummaryType = SummaryItemType.Sum,
                        ShowInColumn = col.FieldName,
                        DisplayFormat = "{0:n2}",
                        FieldName = col.FieldName
                    };
                    gridRows.TotalSummary.Add(summary);
                }
            }
        }
    }
}