using System.Diagnostics.CodeAnalysis;
using System.Windows;
using Core.EntityViewModel;
using Core.ViewModel.Base;
using DevExpress.Xpf.Grid;
using DevExpress.Xpf.Grid.LookUp;
using KursAM2.ViewModel.Reference;
using LayoutManager;
using ILayout = DevExpress.Xpf.Charts.Native.ILayout;

namespace KursAM2.View.KursReferences.KontragentControls
{
    /// <summary>
    ///     Interaction logic for KontragentBankUserControl.xaml
    /// </summary>
    [SuppressMessage("ReSharper", "UnassignedGetOnlyAutoProperty")]
    public partial class KontragentBankUserControl : ILayout
    {
        public KontragentBankUserControl()
        {
            InitializeComponent();
            LayoutManager = new LayoutManager.LayoutManager(GetType().Name, LayoutControl);
            Loaded += MutualAccountingSearchView_Loaded;
            Unloaded += MutualAccountingSearchView_Unloaded;
        }

        public LayoutManagerBase LayoutManager { get; set; }
        public bool Visible { get; }
        public Rect Bounds { get; }
        public Rect[] ClipRects { get; }
        public Rect ClipBounds { get; }
        public Size Size { get; }
        public Point Location { get; }
        public double Angle { get; }

        private void MutualAccountingSearchView_Unloaded(object sender, RoutedEventArgs e)
        {
            LayoutManager.Save();
        }

        private void MutualAccountingSearchView_Loaded(object sender, RoutedEventArgs e)
        {
            LayoutManager.Load();
        }

        private void GridViewBase_OnCellValueChanged(object sender, CellValueChangedEventArgs e)
        {
            var item = e.Row as BankAndAccounts;
            if (item != null) item.State = RowStatus.Edited;
        }

        private void BankGridControl_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            var dtx = DataContext as KontragentCardWindowViewModel;
            foreach (var col in bankGridControl.Columns)
                switch (col.FieldName)
                {
                    case "Bank":
                        if (dtx != null)
                            col.EditSettings = new LookUpEditSettings
                            {
                                DisplayMember = "BANK_NAME",
                                ItemsSource = dtx.AllBanks,
                                AutoPopulateColumns = true
                            };
                        break;
                }
        }

        private void BankGridControl_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
        }
    }
}