using System;
using System.ComponentModel;
using System.Linq;
using System.Windows;
using Core;
using Core.EntityViewModel;
using Core.ViewModel.Base;
using Core.WindowsManager;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Grid;
using DevExpress.Xpf.LayoutControl;
using Helper;
using KursAM2.Dialogs;
using KursAM2.ViewModel.Finance.Invoices;
using LayoutManager;

namespace KursAM2.View.Finance.Invoices
{
    /// <summary>
    ///     Interaction logic for InvoiceForm.xaml
    /// </summary>
    public partial class InvoiceProviderView : ILayout
    {
        private readonly LayoutManagerGridAutoGenerationColumns gridFactsLayout;
        private readonly LayoutManagerGridAutoGenerationColumns gridRowsLayout;
        private readonly LayoutManagerGridAutoGenerationColumns gridPaysLayout;

        public ButtonEdit KontrSelectButton;
        public ComboBoxEdit CurrencyItem { set; get; }

        public InvoiceProviderView()
        {
            InitializeComponent();
            LayoutManager = new LayoutManager.LayoutManager(GetType().Name, this, null);
            gridRowsLayout = new LayoutManagerGridAutoGenerationColumns(GetType().Name, gridRows);
            gridFactsLayout = new LayoutManagerGridAutoGenerationColumns(GetType().Name, gridFacts);
            gridPaysLayout = new LayoutManagerGridAutoGenerationColumns(GetType().Name, gridPays);
            Closing += InvoiceForm_Closing;
            Loaded += InvoiceForm_Loaded;
        }

        public LayoutManagerBase LayoutManager { get; set; }
        public string LayoutManagerName { get; set; }

        private void InvoiceForm_Loaded(object sender, RoutedEventArgs e)
        {
            LayoutManager.Load();
        }

        private void InvoiceForm_Closing(object sender, CancelEventArgs e)
        {
            LayoutManager.Save();
            gridRowsLayout.Save();
            gridFactsLayout.Save();
            gridPaysLayout.Save();
        }

        private void LayoutItems_OnAutoGeneratedUI(object sender, EventArgs e)
        {
            foreach (var item in WindowHelper.GetLogicalChildCollection<MemoEdit>(layoutHeaderItems))
                if (item.EditValue != null && !string.IsNullOrWhiteSpace((string) item.EditValue))
                    item.Height = 80;
        }

        private void LayoutItems_OnAutoGeneratingItem(object sender, DataLayoutControlAutoGeneratingItemEventArgs e)
        {
            var ctx = DataContext as ProviderWindowViewModel;
            var doc = ctx?.Document;
            if (doc == null)
                return;
            var oldContent = e.Item.Content as BaseEdit;
            if (e.PropertyType == typeof(decimal) || e.PropertyType == typeof(decimal?))
            {
                var newContent = new PopupCalcEdit
                {
                    DisplayFormatString = "n2",
                    MaskUseAsDisplayFormat = true
                };
                BindingHelper.CopyBinding(oldContent, newContent, BaseEdit.EditValueProperty);
                e.Item.Content = newContent;
            }
            switch (e.PropertyName)
            {
                case nameof(doc.SF_POSTAV_DATE):
                case nameof(doc.SF_REGISTR_DATE):
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    e.Item.Width = 120;
                    break;
                case nameof(doc.SF_GRUZOOTPRAVITEL):
                case nameof(doc.SF_GRUZOPOLUCHATEL):
                    ViewFluentHelper.SetDefaultMemoEdit(e.Item);
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    e.Item.MinWidth = 400;
                    break;
                case nameof(doc.SF_CRS_SUMMA):
                case nameof(doc.SummaFact):
                case nameof(doc.SF_KONTR_CRS_SUMMA):
                case nameof(doc.NakladAll):
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    e.Item.IsReadOnly = true;
                    e.Item.Width = 300;
                    if (e.Item.Content is PopupCalcEdit ed)
                    {
                        ed.IsReadOnly = true;
                    }
                    break;
                case nameof(doc.Overheads):
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    break;
                case nameof(doc.SF_POSTAV_NUM):
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    break;
                case nameof(doc.SF_IN_NUM):
                    e.Item.IsReadOnly = true;
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    e.Item.Width = 200;
                    break;
                case nameof(doc.Employee):
                    var emplEdit = new ButtonEdit
                    {
                        TextWrapping = TextWrapping.Wrap,
                        IsTextEditable = false
                    };
                    emplEdit.DefaultButtonClick += Employee_DefaultButtonClick;
                    BindingHelper.CopyBinding(oldContent, emplEdit, BaseEdit.EditValueProperty);
                    e.Item.Content = emplEdit;
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    e.Item.MinWidth = 200;
                    break;
                case nameof(doc.TABELNUMBER):
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    break;
                case nameof(doc.CO):
                    ViewFluentHelper.SetComboBoxEdit(e.Item, doc.CO, "CO",
                        MainReferences.COList.Values.ToList().OrderBy(_ => _.Name));
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    e.Item.HorizontalContentAlignment = HorizontalAlignment.Left;
                    break;
                case nameof(doc.FormRaschet):
                    ViewFluentHelper.SetComboBoxEdit(e.Item, doc.FormRaschet, "FormRaschet",
                        MainReferences.FormRaschets.Values.ToList().OrderBy(_ => _.Name));
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    e.Item.HorizontalContentAlignment = HorizontalAlignment.Left;
                    break;
                case nameof(doc.PayCondition):
                    ViewFluentHelper.SetComboBoxEdit(e.Item, doc.PayCondition, "PayCondition",
                        MainReferences.PayConditions.Values.ToList().OrderBy(_ => _.Name));
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    e.Item.HorizontalContentAlignment = HorizontalAlignment.Left;
                    break;
                case nameof(doc.VzaimoraschetType):
                    ViewFluentHelper.SetComboBoxEdit(e.Item, doc.VzaimoraschetType, "VzaimoraschetType",
                        MainReferences.VzaimoraschetTypes.Values.ToList().OrderBy(_ => _.Name));
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    e.Item.HorizontalContentAlignment = HorizontalAlignment.Left;
                    break;
                case nameof(doc.CREATOR):
                    e.Item.IsReadOnly = true;
                    e.Item.HorizontalAlignment = HorizontalAlignment.Right;
                    break;
                case nameof(doc.Currency):
                    CurrencyItem = ViewFluentHelper.SetComboBoxEdit(e.Item, doc.Currency, "Currency",
                        MainReferences.Currencies.Values.ToList(), width:50);
                    if (doc.Rows.Count > 0 && doc.State != RowStatus.NewRow)
                        CurrencyItem.IsEnabled = false;
                    break;
                case nameof(doc.Kontragent):
                    KontrSelectButton = new ButtonEdit
                    {
                        TextWrapping = TextWrapping.Wrap,
                        IsTextEditable = false,
                        Tag = e.PropertyName
                    };
                    KontrSelectButton.DefaultButtonClick += Kontr_DefaultButtonClick;
                    BindingHelper.CopyBinding(oldContent, KontrSelectButton, BaseEdit.EditValueProperty);
                    e.Item.Content = KontrSelectButton;
                    e.Item.MinWidth = 500;
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    break;
                case nameof(doc.KontrReceiver):
                    var kontrEdit = new ButtonEdit
                    {
                        TextWrapping = TextWrapping.Wrap,
                        IsTextEditable = false,
                        Tag = e.PropertyName
                    };
                    kontrEdit.DefaultButtonClick += Kontr_DefaultButtonClick;
                    BindingHelper.CopyBinding(oldContent, kontrEdit, BaseEdit.EditValueProperty);
                    e.Item.Content = kontrEdit;
                    e.Item.MinWidth = 500;
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    break;
                case "State":
                    e.Item.IsReadOnly = true;
                    if (e.Item.Content is ComboBoxEdit cbState) cbState.IsEnabled = false;
                    e.Item.HorizontalAlignment = HorizontalAlignment.Right;
                    break;
                case nameof(doc.SF_NOTES):
                    ViewFluentHelper.SetDefaultMemoEdit(e.Item);
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    e.Item.MinWidth = 300;
                    break;
                case nameof(InvoiceClient.PersonaResponsible):
                    var cb = ViewFluentHelper.SetComboBoxEdit(e.Item, doc.PersonaResponsible, "PersonaResponsible",
                        MainReferences.Employees.Values.ToList().OrderBy(_ => _.Name));
                    var delBtn = new ButtonInfo
                    {
                        GlyphKind = GlyphKind.Cancel,
                    };
                    delBtn.Click += DelBtn_Click;
                    cb.Buttons.Add(delBtn);
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    e.Item.HorizontalContentAlignment = HorizontalAlignment.Left;
                    e.Item.MinWidth = 600;
                    break;
                case nameof(doc.Contract):
                    e.Item.HorizontalAlignment = HorizontalAlignment.Left;
                    e.Item.MinWidth = 300;
                    break;
            }
            ViewFluentHelper.SetModeUpdateProperties(doc, e.Item, e.PropertyName);
        }

        private void DelBtn_Click(object sender, RoutedEventArgs e)
        {
            var ctx = DataContext as ProviderWindowViewModel;
            var doc = ctx?.Document;
            if (doc == null)
                return;
            doc.PersonaResponsible = null;
        }

        private void Kontr_DefaultButtonClick(object sender, RoutedEventArgs e)
        {
            var ctx = DataContext as ProviderWindowViewModel;
            var doc = ctx?.Document;
            if (doc == null)
                return;
            if (doc.PaySumma != 0)
            {
                WindowManager.ShowMessage("По счету есть Оплата. Изменить контрагента нельзя.",
                    "Предупреждение", MessageBoxImage.Information);
                return;
            }
            var kontr = StandartDialogs.SelectKontragent();
            if (kontr == null) return;
            if ((string) (sender as ButtonEdit)?.Tag == "Kontragent")
            {
                ctx.Document.Kontragent = kontr;
                ctx.Document.Currency = kontr.BalansCurrency;
            }
            else
                ctx.Document.KontrReceiver = kontr;
        }

        private void Employee_DefaultButtonClick(object sender, RoutedEventArgs e)
        {
            var ctx = DataContext as ProviderWindowViewModel;
            var doc = ctx?.Document;
            if (doc == null)
                return;
            var emp = StandartDialogs.SelectEmployee();
            if (emp != null) ctx.Document.Employee = emp;
        }

        private void GridRows_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
            if (LayoutManagerBase.ColumnFieldTypeCheckDecimal(e.Column.FieldType))
                e.Column.EditSettings = new CalcEditSettings
                {
                    DisplayFormat = "n2",
                    Name = e.Column.FieldName + "Calc"
                };
            var ctx = DataContext as ProviderWindowViewModel;
            var doc = ctx?.Document;
            if (doc == null)
                return;
            // ReSharper disable once LocalNameCapturedOnly
            // ReSharper disable once RedundantAssignment
            var inv = new InvoiceProviderRow();
            switch (e.Column.Name)
            {
                case nameof(inv.Unit):
                case nameof(inv.NomenklNumber):
                    e.Column.ReadOnly = true;
                    break;
                case nameof(inv.Nomenkl):
                    var nomenklEdit = new ButtonEditSettings
                    {
                        TextWrapping = TextWrapping.Wrap,
                        IsTextEditable = false
                    };
                    nomenklEdit.DefaultButtonClick += Nomenkl_DefaultButtonClick;
                    e.Column.EditSettings = nomenklEdit;
                    break;
                case nameof(inv.Note):
                    e.Column.EditSettings = new MemoEditSettings
                    {
                        ShowIcon = false
                    };
                    break;
                case nameof(inv.KontragentForNaklad):
                    var kontrForNakladEdit = new ButtonEditSettings
                    {
                        TextWrapping = TextWrapping.Wrap,
                        IsTextEditable = false
                    };
                    kontrForNakladEdit.DefaultButtonClick += kontrForNaklad_DefaultButtonClick;
                    e.Column.EditSettings = kontrForNakladEdit;
                    break;
                case nameof(inv.SDRSchet):
                    e.Column.EditSettings = new ComboBoxEditSettings
                    {
                        ItemsSource = MainReferences.SDRSchets.Values,
                        DisplayMember = "Name",
                        ValueMember = "DocCode",
                        AutoComplete = true
                    };
                    break;
            }
        }

        private void kontrForNaklad_DefaultButtonClick(object sender, RoutedEventArgs e)
        {
            var ctx = DataContext as ProviderWindowViewModel;
            var doc = ctx?.Document;
            if (doc == null)
                return;
            if (ctx.CurrentRow == null) return;
            var kontr = StandartDialogs.SelectKontragent();
            if (kontr == null) return;
            ctx.CurrentRow.KontragentForNaklad = kontr;
        }

        private void Nomenkl_DefaultButtonClick(object sender, RoutedEventArgs e)
        {
            decimal defaultNDS;
            var ctx = DataContext as ProviderWindowViewModel;
            var doc = ctx?.Document;
            if (doc == null)
                return;
            var nomenkls = StandartDialogs.SelectNomenkls();
            if (nomenkls == null || nomenkls.Count <= 0) return;
            using (var entctx = GlobalOptions.GetEntities())
            {
                defaultNDS = Convert.ToDecimal(entctx.PROFILE
                    .FirstOrDefault(_ => _.SECTION == "НОМЕНКЛАТУРА" && _.ITEM == "НДС")?.ITEM_VALUE);
            }
            ctx.CurrentRow.Nomenkl = nomenkls.First();
            ctx.CurrentRow.SFT_NDS_PERCENT = ctx.CurrentRow.Nomenkl.NDSPercent ?? defaultNDS;
        }

        private void GridRows_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            var columnsInfo = gridRowsLayout.Load();
            gridRows.TotalSummary.Clear();
            //gridRows.Height = columnsInfo.Height;
            //gridRows.Width = columnsInfo.Width;
            foreach (var col in gridRows.Columns) gridRowsLayout.AutoGeneratedColumnSetProperties(columnsInfo.ColumnsInfo, col);
        }

        private void GridFacts_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
            e.Column.ReadOnly = true;
            if (LayoutManagerBase.ColumnFieldTypeCheckDecimal(e.Column.FieldType))
                e.Column.EditSettings = new CalcEditSettings
                {
                    DisplayFormat = "n2",
                    Name = e.Column.FieldName + "Calc"
                };
        }

        private void GridFacts_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            var columnsInfo = gridFactsLayout.Load();
            gridFacts.TotalSummary.Clear();
            //gridFacts.Height = columnsInfo.Height;
            //gridFacts.Width = columnsInfo.Width;
            foreach (var col in gridFacts.Columns) gridFactsLayout.AutoGeneratedColumnSetProperties(columnsInfo.ColumnsInfo, col);
        }

        private void LayoutHeaderItems_OnAutoGeneratedGroup(object sender,
            DataLayoutControlAutoGeneratedGroupEventArgs e)
        {
            switch (e.Group.Header)
            {
                case "Условия":
                    e.Group.HorizontalAlignment = HorizontalAlignment.Left;
                    break;
            }
        }

        private void GridPays_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
            e.Column.ReadOnly = true;
            if (LayoutManagerBase.ColumnFieldTypeCheckDecimal(e.Column.FieldType))
                e.Column.EditSettings = new CalcEditSettings
                {
                    DisplayFormat = "n2",
                    Name = e.Column.FieldName + "Calc"
                };
        }

        private void GridPays_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            var columnsInfo = gridPaysLayout.Load();
            gridPays.TotalSummary.Clear();
            foreach (var col in gridPays.Columns)
                gridPaysLayout.AutoGeneratedColumnSetProperties(columnsInfo.ColumnsInfo, col);
        }
    }
}