using System.Windows;
using System.Windows.Controls;
using Core.Menu;
using Core.WindowsManager;
using DevExpress.Data;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Grid;
using KursAM2.ViewModel.Finance.Invoices;
using LayoutManager;

namespace KursAM2.View.Finance.Invoices
{
    /// <summary>
    ///     Interaction logic for ProviderSearchView.xaml
    /// </summary>
    public partial class ProviderSearchView : ILayout
    {
        public string LayoutName { set; get; }
        public ProviderSearchView()
        {
            InitializeComponent();
            LayoutManager = new LayoutManager.LayoutManager(GetType().Name, this, gridDocuments);
            Loaded += ProviderSearchView_Loaded;
            Closing += ProviderSearchView_Closing;
        }

        private void ProviderSearchView_Closing(object sender, System.ComponentModel.CancelEventArgs e)
        {
            LayoutManager.Save();
        }

        private void ProviderSearchView_Loaded(object sender, RoutedEventArgs e)
        {
            LayoutManager.Load();
        }

        private void GridDocuments_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
            e.Column.ReadOnly = true;
            switch (e.Column.FieldName)
            {
                case "State":
                    e.Column.Visible = false;
                    break;
                case "SF_NOTES":
                    e.Column.EditSettings = new MemoEditSettings()
                    {
                        ShowIcon = false
                    };
                    break;
            }
        }

        private void GridDocuments_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            gridDocuments.TotalSummary.Clear();
            foreach (var col in gridDocuments.Columns)
            {
                col.ReadOnly = true;
                if (col.FieldType == typeof(decimal) || col.FieldType == typeof(decimal?))
                {
                    col.EditSettings = new CalcEditSettings
                    {
                        AllowDefaultButton = false,
                        DisplayFormat = "n2"
                    };
                    var summary = new GridSummaryItem
                    {
                        SummaryType = SummaryItemType.Sum,
                        ShowInColumn = col.FieldName,
                        DisplayFormat = "{0:n2}",
                        FieldName = col.FieldName
                    };
                    gridDocuments.TotalSummary.Add(summary);
                }
            }
        }

        public LayoutManager.LayoutManager LayoutManager { get; set; }
        public string LayoutManagerName { get; set; }

        private void MenuButton_OnClick(object sender, RoutedEventArgs e)
        {
            var ctx = DataContext as ProviderWindowViewModel;
            if (ctx != null)
            {
                ctx.IsLoading = true;
            }
            var menu = sender as Button;
            if (!(menu?.DataContext is MenuButtonInfo d) || d.SubMenu.Count == 0) return;
            d.MenuOpen(this);
        }
    }
}