using System.ComponentModel;
using System.Windows;
using System.Windows.Controls;
using Core.Menu;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Grid;
using LayoutManager;

namespace KursAM2.View.Finance.Invoices
{
    /// <summary>
    ///     Interaction logic for ProviderSearchView.xaml
    /// </summary>
    public partial class ProviderSearchView : ILayout
    {
        private LayoutManagerGridAutoGenerationColumns myResultGridControlLayout;

        public ProviderSearchView()
        {
            InitializeComponent();
            LayoutManager = new LayoutManager.LayoutManager(GetType().Name, this, null);
            Loaded += ProviderSearchView_Loaded;
            Closing += ProviderSearchView_Closing;
        }

        public string LayoutName { set; get; }

        public LayoutManager.LayoutManager LayoutManager { get; set; }
        public string LayoutManagerName { get; set; }
        public void SaveLayout()
        {
            myResultGridControlLayout.Save();
            LayoutManager.Save();
        }

        private void ProviderSearchView_Closing(object sender, CancelEventArgs e)
        {
            LayoutManager.Save();
            myResultGridControlLayout.Save();
        }

        private void ProviderSearchView_Loaded(object sender, RoutedEventArgs e)
        {
            LayoutManager.Load();
        }

        private void GridDocuments_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
            e.Column.ReadOnly = true;
            switch (e.Column.FieldName)
            {
                case "State":
                    e.Column.Visible = false;
                    break;
                case "SF_NOTES":
                    e.Column.EditSettings = new TextEditSettings
                    {
                        AcceptsReturn = true
                    };
                    break;
            }
        }

        private void GridDocuments_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            myResultGridControlLayout = new LayoutManagerGridAutoGenerationColumns(GetType().Name, gridDocuments);
            LayoutManager.RegistrControlLayouts(myResultGridControlLayout);

            var columnsInfo = myResultGridControlLayout.Load();
            gridDocuments.TotalSummary.Clear();
            foreach (var col in gridDocuments.Columns)
            {
                myResultGridControlLayout.AutoGeneratedColumnSetProperties(columnsInfo.ColumnsInfo, col);
                col.ReadOnly = true;
            }
        }

        private void MenuButton_OnClick(object sender, RoutedEventArgs e)
        {
            var menu = sender as Button;
            if (!(menu?.DataContext is MenuButtonInfo d) || d.SubMenu.Count == 0) return;
            d.MenuOpen(this);
        }
    }
}