using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using Core.Helper;
using Core.ViewModel.Base;
using Data;
using DevExpress.Mvvm.DataAnnotations;

namespace Core.ViewModel.Common
{
    /// <summary>
    ///     Класс контракта для Центров ответственности
    /// </summary>
    [DataContract]
    [MetadataType(typeof(DataAnnotationCentrOfResponsibility))]
    public class CentrOfResponsibility : RSViewModelBase, IEntity<SD_40>
    {
        private SD_40 myEntity;

        [Display(AutoGenerateField = false)]
        public SD_40 Entity
        {
            get => myEntity;
            set
            {
                if (myEntity == value) return;
                myEntity = value;
                RaisePropertyChanged();
            }
        }

        public bool IsAccessRight { get; set; }

        public List<SD_40> LoadList()
        {
            var data = GetAllFromDataBase();
            return data.Select(_ => _.Entity).ToList();
        }

        public override string ToString()
        {
            return Name;
        }

        public IList<CentrOfResponsibility> GetAllFromDataBase()
        {
            return GlobalOptions.GetEntities().SD_40.Select(item => new CentrOfResponsibility(item)).ToList();
        }

        #region Constructor

        public CentrOfResponsibility()
        {
            Entity = DefaultValue();
        }

        public CentrOfResponsibility(SD_40 entity)
        {
            Entity = entity ?? DefaultValue();
        }

        #endregion

        #region Properties

        [Display(AutoGenerateField = false)]
        public override decimal DocCode
        {
            get => Entity.DOC_CODE;
            set
            {
                if (Entity.DOC_CODE == value)
                    return;
                Entity.DOC_CODE = value;
                RaisePropertyChanged();
            }
        }

        [Display(AutoGenerateField = false)]
        public decimal? CentParentDC
        {
            get => Entity.CENT_PARENT_DC;
            set
            {
                if (Entity.CENT_PARENT_DC == value)
                    return;
                Entity.CENT_PARENT_DC = value;
                RaisePropertyChanged();
            }
        }

        //[Display(Name = "Наименование")]
        public override string Name
        {
            get => Entity.CENT_NAME;
            set
            {
                if (Entity.CENT_NAME == value)
                    return;
                Entity.CENT_NAME = value;
                RaisePropertyChanged();
            }
        }

        [Display(Name = "Полное наименование")]
        public string FullName
        {
            get => Entity.CENT_FULLNAME;
            set
            {
                if (Entity.CENT_FULLNAME == value)
                    return;
                Entity.CENT_FULLNAME = value;
                RaisePropertyChanged();
            }
        }

        [Display(Name = "Удален")]
        public bool IsDeleted
        {
            get => Entity.IS_DELETED == 1;
            set
            {
                if (Entity.IS_DELETED == (value ? 1: 0))
                    return;
                Entity.IS_DELETED = value ? 1: 0;
                RaisePropertyChanged();
            }
        }

        [Display(AutoGenerateField = false)]
        public SD_40 SD_402
        {
            get => Entity.SD_402;
            set
            {
                if (Entity.SD_402 == value) return;
                Entity.SD_402 = value;
                RaisePropertyChanged();
            }
        }

        #endregion

        #region Methods

        public void UpdateFrom(SD_40 ent)
        {
            FullName = ent.CENT_FULLNAME;
            Name = ent.CENT_NAME;
            CentParentDC = ent.CENT_PARENT_DC;
            IsDeleted = ent.IS_DELETED == 1;
            SD_402 = ent.SD_402;
        }

        public SD_40 DefaultValue()
        {
            return new SD_40
            {
                DOC_CODE = -1
            };
        }

        #endregion
    }

    public class DataAnnotationCentrOfResponsibility : DataAnnotationForFluentApiBase, IMetadataProvider<CentrOfResponsibility>
    {
        void IMetadataProvider<CentrOfResponsibility>.BuildMetadata(MetadataBuilder<CentrOfResponsibility> builder)
        {
            SetNotAutoGenerated(builder);
            builder.Property(_ => _.Name).AutoGenerated().DisplayName("Краткое наименование");
            builder.Property(_ => _.FullName).AutoGenerated().DisplayName("Полное наименование");
            builder.Property(_ => _.Note).AutoGenerated().DisplayName("Примечание");
        }
    }
}