using System.Windows;
using System.Windows.Controls;
using DevExpress.Xpf.Core;
using DevExpress.Xpf.Grid;

namespace KursAM2.View.DialogUserControl.Invoices.UserControls
{
    /// <summary>
    ///     Interaction logic for InvoiceListView.xaml
    /// </summary>
    public partial class InvoiceListView : UserControl
    {
        public InvoiceListView()
        {
            InitializeComponent(); 
            
        }

        private void GridControlSearch_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
        }

        private void GridControlSearch_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
        }

        private void GridControlPosition_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
        }

        private void GridControlPosition_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
        }
    }
}
