using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using DevExpress.Xpf.Grid;

namespace KursAM2.View.DialogUserControl.Invoices.UserControls
{
    /// <summary>
    /// Interaction logic for InvoiceListSearchView.xaml
    /// </summary>
    public partial class InvoiceListSearchView : UserControl
    {
        public InvoiceListSearchView()
        {
            InitializeComponent();
        }

        private void GridControlSearch_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
        }

        private void GridControlSearch_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {

        }

        private void GridControlPosition_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
        }

        private void GridControlPosition_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            
        }
    }
}
