using System;
using System.ComponentModel;
using System.Linq;
using System.Windows;
using DevExpress.Xpf.Grid;
using KursAM2.ViewModel.Management;
using LayoutManager;

namespace KursAM2.View.Management
{
    /// <summary>
    ///     Interaction logic for ProjectProfitAndLossView.xaml
    /// </summary>
    public partial class ProjectProfitAndLossView : ILayout
    {
        public ProjectProfitAndLossView()
        {
            InitializeComponent();
            LayoutManager = new LayoutManager.LayoutManager(GetType().Name, this, mainLayoutControl);
            Closing += OnClosing;
            Loaded += ProfitAndLosses_Loaded;
            DataContextChanged += ManagementBalansView_DataContextChanged;
        }

        public LayoutManager.LayoutManager LayoutManager { get; set; }
        public string LayoutManagerName { get; set; }

        private void ManagementBalansView_DataContextChanged(object sender, DependencyPropertyChangedEventArgs e)
        {
            if (DataContext is ProfitAndLossesWindowViewModel ctx)
                // ReSharper disable once PossibleNullReferenceException
                Dispatcher.BeginInvoke((Action) (() => rateCrsRecalc.EditValue =
                    ctx.CurrenciesForRecalc.First(_ => _.Name == "RUR" || _.Name == "RUB")));
        }

        private void ProfitAndLosses_Loaded(object sender, RoutedEventArgs e)
        {
            //Title = "Прибыли и убытки. База данных " + GlobalOptions.DataBaseName;
            LayoutManager.Load();
        }

        private void OnClosing(object sender, CancelEventArgs cancelEventArgs)
        {
            LayoutManager.Save();
        }

        private void GridControlMain_OnSelectedItemChanged(object sender, SelectedItemChangedEventArgs e)
        {
            if (!(DataContext is ProjectProfitAndLossesWindowViewModel ctx)) return;
            if (e.NewItem is ProfitAndLossesMainRowViewModel v) ctx.UpdateExtend(v.Id);
            if (!(e.NewItem is ProfitAndLossesMainRowViewModel item))
            {
                col124.Visible = false;
                return;
            }
            col124.Visible = item.Name == "Финансовые операции";
        }

        private void GridRate_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
        }
    }
}