using System;
using System.Linq;
using System.Windows;
using Core;
using Core.EntityViewModel.CommonReferences;
using Core.WindowsManager;
using DevExpress.Xpf.Core;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Grid;
using DevExpress.Xpf.Grid.DragDrop;
using KursAM2.ViewModel.Reference;
using LayoutManager;

namespace KursAM2.View.KursReferences
{
    /// <summary>
    ///     Interaction logic for ProjectReferenceView.xaml
    /// </summary>
    public partial class ProjectReferenceView : ILayout
    {
        private readonly ButtonEditSettings myBnEditor;

        public ProjectReferenceView()
        {
            InitializeComponent(); 
            ApplicationThemeHelper.ApplicationThemeName = Theme.MetropolisLightName;
            myBnEditor = new ButtonEditSettings
            {
                IsTextEditable = false
            };
            myBnEditor.DefaultButtonClick += MyBnEditor_DefaultButtonClick;
            LayoutManager = new LayoutManager.LayoutManager(GetType().Name, this, treeListControl);
            Loaded += ProjectReferenceView_Loaded;
            Unloaded += ProjectReferenceView_Unloaded;
        }

        public LayoutManager.LayoutManager LayoutManager { get; set; }
        public string LayoutManagerName { get; set; }
        public void SaveLayout()
        {
            LayoutManager.Save();
        }

        private void MyBnEditor_DefaultButtonClick(object sender, RoutedEventArgs e)
        {
            var ctx = DataContext as ProjectReferenceWindowViewModel;
            ctx?.SetResponsible();
            treeListView.CloseEditor();
        }

        private void ProjectReferenceView_Unloaded(object sender, RoutedEventArgs e)
        {
            LayoutManager.Save();
        }

        private void ProjectReferenceView_Loaded(object sender, RoutedEventArgs e)
        {
            var i = 0;
            foreach (var band in treeListControl.Bands)
            {
                band.Name = "band" + i;
                ++i;
            }
            LayoutManager.Load();
            foreach (var band in treeListControl.Bands)
                switch (band.Header)
                {
                    case "CHF":
                    case "SEK":
                    case "EUR":
                    case "RUB":
                    case "GBP":
                    case "USD":
                        band.Visible = false;
                        break;
                }
        }

        private void TreeListControl_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
        }

        private void TreeListControl_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            foreach (var col in treeListControl.Columns)
                if (col.Name == "Responsible")
                    col.EditSettings = myBnEditor;
        }

        public Project dropProject { set; get; } 

        private void TreeListDragDropManager_Drop(object sender, TreeListDropEventArgs e)
        {
            if (!(e.TargetNode.Content is Project t) || dropProject == null) return;
            dropProject.ParentId = t.Id;
            using (var ctx = GlobalOptions.GetEntities())
            {
                var tx = ctx.Database.BeginTransaction();
                try
                {
                    var prj = ctx.Projects.FirstOrDefault(_ => _.Id == dropProject.Id);
                    {
                        if (prj != null)
                        {
                            prj.ParentId = t.Id;
                        }
                    }
                    ctx.SaveChanges();
                    tx.Commit();
                }

                catch (Exception ex)
                {
                    tx.Rollback();
                    WindowManager.ShowError(ex);
                }
            }

        }

        private void TreeListDragDropManager_DragOver(object sender, TreeListDragOverEventArgs e)
        {
            if (!(DataContext is ProjectReferenceWindowViewModel dtx)) return;
            dropProject = dtx.CurrentProject;
        }
    }
}
