using System.Linq;
using System.Windows;
using System.Windows.Input;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Grid;
using KursAM2.ViewModel.Reference;
using KursDomain;
using KursDomain.References;

namespace KursAM2.View.KursReferences;

/// <summary>
///     Interaction logic for ProjectReferenceView.xaml
/// </summary>
public partial class ProjectReferenceView
{
    public ProjectReferenceView()
    {
        InitializeComponent();
    }

    private void GridProjects_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
    {
        e.Column.Name = e.Column.FieldName;
        ICommand delCommand = null;
        if (DataContext is ProjectReferenceWindowViewModel vm) delCommand = vm.DeleteManagerCommand;
        switch (e.Column.Name)
        {
            case "Responsible":
                e.Column.EditSettings = new ComboBoxEditSettings
                {
                    ItemsSource = GlobalOptions.ReferencesCache.GetEmployees().Cast<Employee>()
                        .OrderBy(_ => _.Name).ToList(),
                    DisplayMember = "Name",
                    AutoComplete = true,
                    Buttons =
                    {
                        new ButtonInfo
                        {
                            GlyphKind = GlyphKind.Cancel,
                            Command = delCommand
                        }
                    }
                };
                break;
        }
    }

    private void GridProjects_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
    {
    }

    private void GridGroupProjects_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
    {
        e.Column.Name = e.Column.FieldName;
    }

    private void GridGroupProjects_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
    {
    }

    private void GridLinkGroupProjects_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
    {
        e.Column.Name = e.Column.FieldName;
    }

    private void GridLinkGroupProjects_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
    {
    }
}
