using Core;
using Core.WindowsManager;
using DevExpress.Xpf.Grid;
using DevExpress.Xpf.Grid.DragDrop;
using KursAM2.ViewModel.Reference;
using LayoutManager;
using System;
using System.ComponentModel;
using System.Linq;
using System.Windows;
using Core.EntityViewModel.CommonReferences;
using DevExpress.Xpf.Core;

namespace KursAM2.View.KursReferences
{
    /// <summary>
    ///     Interaction logic for ReferenceOfResponsibilityCentersView.xaml
    /// </summary>
    public partial class ReferenceOfResponsibilityCentersView : ILayout
    {


        public ReferenceOfResponsibilityCentersView()
        {
            InitializeComponent(); 
            ApplicationThemeHelper.ApplicationThemeName = Theme.MetropolisLightName;

            LayoutManager = new LayoutManager.LayoutManager(GetType().Name, this, treeListControl);
            Loaded += ReferenceOfResponsibilityCentersView_Loaded;
            Closing += ReferenceOfResponsibilityCentersView_Closing;
            
        }

        public LayoutManager.LayoutManager LayoutManager { get; set; }

        public string LayoutManagerName { get; set; }
        public void SaveLayout()
        {
            LayoutManager.Save();
        }

        private void ReferenceOfResponsibilityCentersView_Closing(object sender, CancelEventArgs e)
        {
            LayoutManager.Save();
        }

        private void ReferenceOfResponsibilityCentersView_Loaded(object sender, RoutedEventArgs e)
        {
            LayoutManager.Load();
        }

        private void TreeListControl_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
            //if (e.Column.FieldName == "Note")
            //    e.Column.Visible = false;
        }
        private void TreeListControl_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            
        }

        public CentrOfResponsibility dropCenter { set; get; }

        private void TreeListDragDropManager_Drop(object sender, TreeListDropEventArgs e)
        {
            if (!(e.TargetNode.Content is CentrOfResponsibility t) || dropCenter == null) return;
            dropCenter.CentParentDC = t.DocCode;
            using (var ctx = GlobalOptions.GetEntities())
            {
                var tx = ctx.Database.BeginTransaction();
                try
                {
                    var centr = ctx.SD_40.FirstOrDefault(_ => _.DOC_CODE == dropCenter.DocCode);
                    {
                        if (centr != null)
                        {
                            centr.CENT_PARENT_DC = t.DocCode;
                        }
                    }
                    ctx.SaveChanges();
                    tx.Commit();
                }

                catch (Exception ex)
                {
                    tx.Rollback();
                    WindowManager.ShowError(ex);
                }
            }

        }

        private void TreeListDragDropManager_DragOver(object sender, TreeListDragOverEventArgs e)
        {
            if (!(DataContext is ReferenceOfResponsibilityCentersWindowViewModel dtx)) return;
            dropCenter = dtx.CurrentCenter;
        }



    }
}
