using System.ComponentModel;
using System.Windows;
using DevExpress.Xpf.Core;
using DevExpress.Xpf.Grid;
using LayoutManager;

namespace KursAM2.View.KursReferences
{
    /// <summary>
    ///     Interaction logic for SDRReferenceView.xaml
    /// </summary>
    public partial class SDRReferenceView : ILayout
    {
        public SDRReferenceView()
        {
            InitializeComponent();
            ApplicationThemeHelper.ApplicationThemeName = Theme.MetropolisLightName;
            LayoutManager = new LayoutManager.LayoutManager(GetType().Name, this, MainLayoutControl);
            Loaded += SDRReferenceView_Loaded;
            Closing += SDRReferenceView_Closing;
        }

        public LayoutManager.LayoutManager LayoutManager { get; set; }
        public string LayoutManagerName { get; set; }

        public void SaveLayout()
        {
            LayoutManager.Save();
        }

        private void SDRReferenceView_Closing(object sender, CancelEventArgs e)
        {
            LayoutManager.Save();
        }

        private void SDRReferenceView_Loaded(object sender, RoutedEventArgs e)
        {
            LayoutManager.Load();
        }

        private void treeListSDRState_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
        }

        private void treeListSDRState_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
        }

        private void GridControlSDRSchet_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
        }

        private void GridControlSDRSchet_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
        }
    }
}
