using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Core.EntityViewModel.Bank;
using Core.EntityViewModel.Cash;
using Core.EntityViewModel.CommonReferences;
using Core.Helper;
using Core.ViewModel.Base;
using Data;
using DevExpress.Mvvm.DataAnnotations;

namespace Core.EntityViewModel.AccruedAmount
{

    public class AccruedAmountOfSupplierRowViewModel_FluentAPI : DataAnnotationForFluentApiBase,
        IMetadataProvider<AccruedAmountOfSupplierRowViewModel>
    {
        void IMetadataProvider<AccruedAmountOfSupplierRowViewModel>.BuildMetadata(MetadataBuilder<AccruedAmountOfSupplierRowViewModel> builder)
        {
            SetNotAutoGenerated(builder);
            builder.Property(_ => _.Entity).NotAutoGenerated();
            builder.Property(_ => _.Parent).NotAutoGenerated();
            builder.Property(_ => _.Error).NotAutoGenerated();
            builder.Property(_ => _.Name).NotAutoGenerated();
            builder.Property(_ => _.AccruedAmountType).AutoGenerated().DisplayName("Начисление")
                .NullDisplayText("Введите тип начисления");
            builder.Property(_ => _.Summa).AutoGenerated().DisplayName("Сумма").DisplayFormatString("n2");
            builder.Property(_ => _.PaySumma).AutoGenerated().DisplayName("Сумма оплачено")
                .DisplayFormatString("n2").ReadOnly();
            builder.Property(_ => _.Note).AutoGenerated().DisplayName("Примечание");
            builder.Property(_ => _.CashDoc).AutoGenerated().DisplayName("Приходный касс.ордер");
            builder.Property(_ => _.BankDoc).AutoGenerated().DisplayName("Банковская транзакция");
            builder.Property(_ => _.SDRSchet).AutoGenerated().DisplayName("Счет дох/расх");

        }
    }
    [MetadataType(typeof(AccruedAmountOfSupplierRowViewModel_FluentAPI))]
    public class AccruedAmountOfSupplierRowViewModel : RSViewModelBase, IDataErrorInfo
    {

        #region Fields

        private AccuredAmountOfSupplierRow myEntity;
        private AccruedAmountOfSupplierViewModel myParent;
        private SDRSchet mySDRSchet;
        private CashOut myCashDoc;
        private BankOperationsViewModel myBankDoc;

        #endregion

        #region Properties
        
        public new AccruedAmountOfSupplierViewModel Parent
        {
            get => myParent;
            set
            {
                if (myParent == value) return;
                myParent = value;
                RaisePropertyChanged();
            }
        }

        public AccuredAmountOfSupplierRow Entity
        {
            get => myEntity;
            set
            {
                if (myEntity == value) return;
                myEntity = value;
                RaisePropertyChanged();
            }
        }

        public override Guid Id
        {
            get => Entity.Id;
            set
            {
                if (Entity.Id == value) return;
                Entity.Id = value;
                RaisePropertyChanged();
            }
        }

        public Guid DocId
        {
            get => Entity.DocId;
            set
            {
                if (Entity.DocId == value) return;
                Entity.DocId = value;
                RaisePropertyChanged();
            }
        }

        public AccruedAmountTypeViewModel AccruedAmountType
        {
            get => MainReferences.GetAccruedAmountType(Entity.AccuredAmountTypeId);
            set
            {
                if (MainReferences.GetAccruedAmountType(Entity.AccuredAmountTypeId) == value) return;
                if (value != null)
                {
                    Entity.AccuredAmountTypeId = value.Id;
                    RaisePropertyChanged();
                }
            }
        }
        public decimal PaySumma => CashDoc?.SUMM_ORD ?? 0 + BankDoc?.VVT_VAL_PRIHOD ?? 0;
        public decimal Summa
        {
            get => Entity.Summa;
            set
            {
                if (Entity.Summa == value) return;
                Entity.Summa = value;
                RaisePropertyChanged();
            }
        }

        public SDRSchet SDRSchet
        {
            get => mySDRSchet;
            set
            {
                if (mySDRSchet == value) return;
                mySDRSchet = value;
                Entity.SHPZ_DC = value?.DocCode;
                RaisePropertyChanged();
            }
        }
        public CashOut CashDoc
        {
            get => myCashDoc;
            set
            {
                if (myCashDoc == value) return;
                myCashDoc = value;
                Entity.CashDC = value?.DocCode;
                RaisePropertyChanged();
                RaisePropertyChanged(nameof(PaySumma));
            }
        }

        public BankOperationsViewModel BankDoc
        {
            get => myBankDoc;
            set
            {
                if (myBankDoc == value) return;
                myBankDoc = value;
                Entity.BankCode = value?.Code;
                RaisePropertyChanged();
                RaisePropertyChanged(nameof(PaySumma));
            }
        }

        public override string Note
        {
            get => Entity.Note;
            set
            {
                if (Entity.Note == value) return;
                Entity.Note = value;
                RaisePropertyChanged();
            }
        }
        #endregion

        #region Constructors

        public AccruedAmountOfSupplierRowViewModel(AccuredAmountOfSupplierRow entity, 
            AccruedAmountOfSupplierViewModel parent = null)
        {
            Entity = entity ?? DefaultValue();
            if (parent != null)
            {
                Parent = parent;
                Entity.DocId = parent.Id;
            }
        }

        private AccuredAmountOfSupplierRow DefaultValue()
        {
            return new AccuredAmountOfSupplierRow
            {
                Id = Guid.NewGuid(),
                Summa = 0,
            };
        }

        #endregion

        #region IDataErrorInfo

        public string this[string columnName]
        {
            get
            {
                switch (columnName)
                {
                    case nameof(AccruedAmountType):
                        return AccruedAmountType == null ? "Тип начисления должен быть обязательно выбран" : null;
                    case nameof(Summa):
                        return Summa <= 0 ? "Сумма должна быть больше 0" : null;
                    default:
                        return null;
                }
            }
        }

        public string Error => null;

        #endregion
    }
}