//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD_149
    {
        public decimal APB_NOMENKL_DC { get; set; }
        public decimal APB_CENTR_OTV_DC { get; set; }
        public System.DateTime APB_DATE { get; set; }
        public double APB_KOL { get; set; }
        public Nullable<decimal> APB_NOM_PRICE { get; set; }
        public Nullable<decimal> APB_UCH_PRICE { get; set; }
        public Nullable<double> APB_KOL_NOT_FACT { get; set; }
    }
}
