//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CROSS_MATER_ANAL
    {
        public System.DateTime PERIOD_START { get; set; }
        public System.DateTime PERIOD_STOP { get; set; }
        public int SCHET { get; set; }
        public int SUBSCHET { get; set; }
        public string SKLAD_POLUCH { get; set; }
        public short N_PP { get; set; }
        public Nullable<decimal> OSTAT_VHOD { get; set; }
        public Nullable<decimal> PRIHOD { get; set; }
        public Nullable<decimal> RASHOD { get; set; }
        public Nullable<decimal> OSTAT_ISHOD { get; set; }
        public string OTPRAVITEL { get; set; }
        public Nullable<decimal> SUMMA { get; set; }
    }
}
