//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXT_POKAZ_VALUES
    {
        public string PZ_ID { get; set; }
        public int DB_ID { get; set; }
        public double PZV_ABSOLUT_VALUE { get; set; }
        public double PZV_REFERENTIAL_VALUE { get; set; }
        public int PZV_PERIOD_FLAG { get; set; }
        public System.DateTime PZV_DATE_FROM { get; set; }
        public System.DateTime PZV_DATE_TO { get; set; }
        public Nullable<System.DateTime> PZV_CALC_DATE { get; set; }
    
        public virtual EXT_POKAZ EXT_POKAZ { get; set; }
    }
}
