//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXT_DDE_SERVERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXT_DDE_SERVERS()
        {
            this.EXT_PRINT = new HashSet<EXT_PRINT>();
            this.EXT_USER_PRINT = new HashSet<EXT_USER_PRINT>();
        }
    
        public int DDE_ID { get; set; }
        public string DDE_SERVER { get; set; }
        public string DDE_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_PRINT> EXT_PRINT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_USER_PRINT> EXT_USER_PRINT { get; set; }
    }
}
