//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXT_USER_PRINT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXT_USER_PRINT()
        {
            this.EXT_BUH_REP_DISCR = new HashSet<EXT_BUH_REP_DISCR>();
            this.EXT_PRINT_MASS = new HashSet<EXT_PRINT_MASS>();
        }
    
        public int RD_ID { get; set; }
        public string RD_REPORT_NAME { get; set; }
        public string RD_QRP_GRAPH { get; set; }
        public string RD_DDE_TEMPLATE { get; set; }
        public string RD_INPUTS { get; set; }
        public int SP_ID { get; set; }
        public Nullable<short> RD_USERFLAG { get; set; }
        public Nullable<int> PI_ID { get; set; }
        public Nullable<short> RD_FIRST_TABLE_ROW { get; set; }
        public Nullable<int> DDE_ID { get; set; }
        public Nullable<short> RD_REPORT_TYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_BUH_REP_DISCR> EXT_BUH_REP_DISCR { get; set; }
        public virtual EXT_DDE_SERVERS EXT_DDE_SERVERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_PRINT_MASS> EXT_PRINT_MASS { get; set; }
        public virtual EXT_PRINTIERARHY EXT_PRINTIERARHY { get; set; }
        public virtual EXT_USER_PROC EXT_USER_PROC { get; set; }
    }
}
