//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXT_CROSSTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXT_CROSSTBL()
        {
            this.TYPES = new HashSet<TYPES>();
        }
    
        public int CR_ID { get; set; }
        public int SP_ID { get; set; }
        public string CR_NAME { get; set; }
        public string CR_PRIHOD_PREFIX { get; set; }
        public string CR_RASHOD_PREFIX { get; set; }
        public short CR_STATIC_COLS { get; set; }
        public Nullable<short> CR_PRIH_ITOG_FLAG { get; set; }
        public Nullable<short> CR_RASH_ITOG_FLAG { get; set; }
        public Nullable<int> CR_ACC { get; set; }
        public Nullable<int> SP_GENERATE_ID { get; set; }
    
        public virtual EXT_PROC EXT_PROC { get; set; }
        public virtual EXT_PROC EXT_PROC1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TYPES> TYPES { get; set; }
    }
}
