//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXT_USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXT_USERS()
        {
            this.EXT_AUTO_PROC_EXEC = new HashSet<EXT_AUTO_PROC_EXEC>();
            this.EXT_AUTO_PROC_START = new HashSet<EXT_AUTO_PROC_START>();
            this.EXT_MESSAGES_NOTES = new HashSet<EXT_MESSAGES_NOTES>();
            this.PERIOD_GROUPS_USERS = new HashSet<PERIOD_GROUPS_USERS>();
            this.EXT_MESSAGES_NOTES1 = new HashSet<EXT_MESSAGES_NOTES>();
            this.EXT_GROUPS = new HashSet<EXT_GROUPS>();
            this.SD_102 = new HashSet<SD_102>();
            this.SD_114 = new HashSet<SD_114>();
            this.SD_201 = new HashSet<SD_201>();
            this.SD_213 = new HashSet<SD_213>();
            this.SD_22 = new HashSet<SD_22>();
            this.SD_257 = new HashSet<SD_257>();
            this.SD_264 = new HashSet<SD_264>();
            this.SD_27 = new HashSet<SD_27>();
            this.SD_271 = new HashSet<SD_27>();
            this.SD_272 = new HashSet<SD_27>();
            this.SD_298 = new HashSet<SD_298>();
            this.SD_303 = new HashSet<SD_303>();
            this.SD_396 = new HashSet<SD_396>();
            this.SD_40 = new HashSet<SD_40>();
            this.SD_77 = new HashSet<SD_77>();
            this.SD_82 = new HashSet<SD_82>();
            this.SD_270 = new HashSet<SD_270>();
            this.SD_17 = new HashSet<SD_17>();
        }
    
        public int USR_ID { get; set; }
        public string USR_NICKNAME { get; set; }
        public string USR_FULLNAME { get; set; }
        public Nullable<int> TABELNUMBER { get; set; }
        public string USR_PHONE { get; set; }
        public string USR_NOTES { get; set; }
        public string USR_PASSWORD { get; set; }
        public Nullable<short> USR_PROVODKY { get; set; }
        public Nullable<int> USR_ABORT_CONNECT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_AUTO_PROC_EXEC> EXT_AUTO_PROC_EXEC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_AUTO_PROC_START> EXT_AUTO_PROC_START { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_MESSAGES_NOTES> EXT_MESSAGES_NOTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERIOD_GROUPS_USERS> PERIOD_GROUPS_USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_MESSAGES_NOTES> EXT_MESSAGES_NOTES1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_GROUPS> EXT_GROUPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_102> SD_102 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_114> SD_114 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_201> SD_201 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_213> SD_213 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_22> SD_22 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_257> SD_257 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_264> SD_264 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_27> SD_27 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_27> SD_271 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_27> SD_272 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_298> SD_298 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_303> SD_303 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_396> SD_396 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_40> SD_40 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_77> SD_77 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_82> SD_82 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_270> SD_270 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_17> SD_17 { get; set; }
    }
}
