//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXT_USER_PROCPARS
    {
        public int PPAR_ID { get; set; }
        public short PPAR_NUM_PP { get; set; }
        public int SP_ID { get; set; }
        public short PPAR_SALTYPE { get; set; }
        public short PPAR_ISRECEIVE { get; set; }
        public string PPAR_INTONAME { get; set; }
        public string PPAR_FONT_NAME { get; set; }
        public Nullable<short> PPAR_FONT_SIZE { get; set; }
        public Nullable<short> PPAR_ALIGN { get; set; }
        public Nullable<int> PPAR_BORDERS { get; set; }
        public Nullable<short> PPAR_FONT_ENH { get; set; }
        public string PPAR_COORDS { get; set; }
        public Nullable<short> PPAR_VISIBLE { get; set; }
        public string PPAR_SELECT_DIALOG { get; set; }
    }
}
