//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXT_PRINT2DOC
    {
        public int RD_ID { get; set; }
        public int TABLE_CODE { get; set; }
        public Nullable<short> ADD_TO_MENU { get; set; }
    
        public virtual EXT_PRINT EXT_PRINT { get; set; }
        public virtual TYPES TYPES { get; set; }
    }
}
