//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXT_JOURNAL1
    {
        public System.DateTime J_TIME { get; set; }
        public string J_USER { get; set; }
        public string J_CLIENT { get; set; }
        public decimal J_DOC_CODE { get; set; }
        public string J_NOTES { get; set; }
        public string J_OPERATION { get; set; }
        public decimal J_ID { get; set; }
        public Nullable<short> J_OP_CODE { get; set; }
    }
}
