//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXT_GRP
    {
        public int GRP_ID { get; set; }
        public int TABLE_CODE { get; set; }
        public string GRP_NAME { get; set; }
        public Nullable<short> GRP_NOT_USED { get; set; }
        public Nullable<short> GRP_OUTLINE { get; set; }
        public string GRP_TABLE { get; set; }
        public string GRP_SPR_ID_FIELD { get; set; }
        public string GRP_SPR_TABLE { get; set; }
        public string GRP_SPR_TABLE_ID_FIELD { get; set; }
        public string GRP_SPR_TABLE_NAME_FIELD { get; set; }
        public string GRP_POPULATE_WHERE { get; set; }
    
        public virtual TYPES TYPES { get; set; }
    }
}
