//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class KURS_RAZNICA
    {
        public Nullable<decimal> kontr_dc { get; set; }
        public Nullable<decimal> nom_dc { get; set; }
        public int oper_type { get; set; }
        public System.DateTime oper_date { get; set; }
        public Nullable<decimal> sum_rate { get; set; }
    }
}
