//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class REMAINS_STATUS
    {
        public string ROW_ID { get; set; }
        public string STATUS_ID { get; set; }
        public decimal KOL { get; set; }
    }
}
