//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class REMAINS
    {
        public decimal SKLAD_DC { get; set; }
        public decimal NOM_DC { get; set; }
        public System.DateTime DATE { get; set; }
        public decimal KOL_START { get; set; }
        public decimal KOL_IN { get; set; }
        public decimal KOL_OUT { get; set; }
        public decimal KOL_END { get; set; }
        public string ROW_ID { get; set; }
    }
}
