//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_185
    {
        public decimal DOC_CODE { get; set; }
        public System.DateTime VZ_DATE { get; set; }
        public decimal VZ_S_KOGO_SPISAT_DC { get; set; }
        public decimal VZ_NA_KOGO_POVESIT_DC { get; set; }
        public decimal VZ_CRS_DC { get; set; }
        public Nullable<decimal> VZ_SUMMA { get; set; }
        public string VZ_NOTES { get; set; }
        public byte[] VZ_DOC_OLE { get; set; }
    
        public virtual SD_43 SD_43 { get; set; }
        public virtual SD_43 SD_431 { get; set; }
    }
}
