//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_150
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_150()
        {
            this.TD_150 = new HashSet<TD_150>();
        }
    
        public decimal DOC_CODE { get; set; }
        public System.DateTime POU_MONTH { get; set; }
        public string POU_NOTES { get; set; }
        public short NCODE { get; set; }
        public Nullable<System.DateTime> POU_START_MONTH { get; set; }
        public Nullable<System.DateTime> POU_STOP_MONTH { get; set; }
        public Nullable<double> POU_NUM_NOTE { get; set; }
    
        public virtual VD_46 VD_46 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_150> TD_150 { get; set; }
    }
}
