//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_152
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_152()
        {
            this.TD_152 = new HashSet<TD_152>();
            this.SD_275 = new HashSet<SD_275>();
            this.TD_11 = new HashSet<TD_11>();
            this.TD_17 = new HashSet<TD_17>();
            this.UD_152 = new HashSet<UD_152>();
            this.VD_152 = new HashSet<VD_152>();
            this.WD_152 = new HashSet<WD_152>();
            this.XD_152 = new HashSet<XD_152>();
        }
    
        public decimal DOC_CODE { get; set; }
        public string M_NAME { get; set; }
        public short M_PERIOD { get; set; }
        public short M_SMEN { get; set; }
        public Nullable<short> M_SANDAY_IS_HOL { get; set; }
        public Nullable<short> M_SATURDAY_IS_HOL { get; set; }
        public Nullable<decimal> M_BALANS_DC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_152> TD_152 { get; set; }
        public virtual SD_19 SD_19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_275> SD_275 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_11> TD_11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_17> TD_17 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UD_152> UD_152 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VD_152> VD_152 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WD_152> WD_152 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XD_152> XD_152 { get; set; }
    }
}
