//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_154
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_154()
        {
            this.VD_152 = new HashSet<VD_152>();
        }
    
        public decimal DOC_CODE { get; set; }
        public Nullable<System.DateTime> HOL_DATE { get; set; }
        public string HOL_NAME { get; set; }
        public Nullable<int> HOL_TL_ID { get; set; }
    
        public virtual VD_11 VD_11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VD_152> VD_152 { get; set; }
    }
}
