//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_292
    {
        public decimal DOC_CODE { get; set; }
        public int SOV_NUM { get; set; }
        public System.DateTime SOV_DATE { get; set; }
        public int TABELNUMBER { get; set; }
        public System.DateTime SOV_START_DATE { get; set; }
        public System.DateTime SOV_STOP_DATE { get; set; }
        public double SOV_COEF { get; set; }
        public double SOV_OKLAD { get; set; }
        public int SOV_DOLZH { get; set; }
        public string SOV_REASON { get; set; }
    
        public virtual SD_2 SD_2 { get; set; }
        public virtual TD_17 TD_17 { get; set; }
    }
}
