//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_293
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_293()
        {
            this.SD_294 = new HashSet<SD_294>();
        }
    
        public decimal DOC_CODE { get; set; }
        public int VV_NUM { get; set; }
        public System.DateTime VV_DATE { get; set; }
        public System.DateTime VV_FROM { get; set; }
        public int TABELNUMBER { get; set; }
        public int VV_SHTAT_CODE { get; set; }
        public decimal VV_TYPE_DC { get; set; }
        public string VV_REASON { get; set; }
    
        public virtual SD_2 SD_2 { get; set; }
        public virtual TD_17 TD_17 { get; set; }
        public virtual SD_296 SD_296 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_294> SD_294 { get; set; }
    }
}
