//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_264
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_264()
        {
            this.SD_265 = new HashSet<SD_265>();
            this.EXT_USERS = new HashSet<EXT_USERS>();
        }
    
        public decimal DOC_CODE { get; set; }
        public string OT_NAME { get; set; }
        public short OT_USE_IN_TABEL { get; set; }
        public string OT_TABEL_SYMBOL { get; set; }
        public Nullable<short> OT_PROGUL { get; set; }
        public short OT_DELETED { get; set; }
        public short OT_MATREFLECTION { get; set; }
        public Nullable<int> TL_ID { get; set; }
        public Nullable<int> OT_OP_CODE { get; set; }
        public Nullable<double> OT_HOURS_PER_DAY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_265> SD_265 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_USERS> EXT_USERS { get; set; }
    }
}
