//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_258
    {
        public decimal DOC_CODE { get; set; }
        public int ZAM_NUM { get; set; }
        public System.DateTime ZAM_DATE { get; set; }
        public int TABELNUMBER { get; set; }
        public Nullable<int> ZAM_TABELNUMBER { get; set; }
        public int ZAM_SHTAT_CODE { get; set; }
        public System.DateTime ZAM_FROM { get; set; }
        public System.DateTime ZAM_TO { get; set; }
        public decimal ZAM_OKLAD { get; set; }
        public string ZAM_NOTES { get; set; }
        public Nullable<decimal> ZAM_GRAFIK_RV_DC { get; set; }
    
        public virtual SD_2 SD_2 { get; set; }
        public virtual SD_2 SD_21 { get; set; }
        public virtual TD_17 TD_17 { get; set; }
    }
}
