//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_289
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_289()
        {
            this.SD_219 = new HashSet<SD_219>();
            this.SD_299 = new HashSet<SD_299>();
            this.SD_302 = new HashSet<SD_302>();
            this.SD_306 = new HashSet<SD_306>();
        }
    
        public decimal DOC_CODE { get; set; }
        public System.DateTime ZC_MONTH { get; set; }
        public short ZC_TABEL_EXECUTED { get; set; }
        public short ZC_NACH_EXECUTED { get; set; }
        public short ZC_RAS_EXECUTED { get; set; }
        public short ZC_PLAT_EXECUTED { get; set; }
        public Nullable<decimal> ZC_NU_DC { get; set; }
        public Nullable<short> ZC_RAS_NEED_RECALC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_219> SD_219 { get; set; }
        public virtual SD_46 SD_46 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_299> SD_299 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_302> SD_302 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_306> SD_306 { get; set; }
    }
}
