//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_308
    {
        public decimal DOC_CODE { get; set; }
        public System.DateTime ACTOUT_DATE { get; set; }
        public int ACTOUT_NUM { get; set; }
        public string ACTOUT_OPER { get; set; }
        public decimal ACTOUT_OS_DC { get; set; }
        public string ACTOUT_DOCS { get; set; }
    
        public virtual SD_122 SD_122 { get; set; }
    }
}
