//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_315
    {
        public decimal LU_ID { get; set; }
        public int TE_ID { get; set; }
        public string LU_NPF_REGISTR_NUM { get; set; }
        public string LU_NAME_LAST { get; set; }
        public string LU_NAME_FIRST { get; set; }
        public string LU_NAME_SECOND { get; set; }
        public string LU_NAME { get; set; }
        public string LU_SEX { get; set; }
        public int TABELNUMBER { get; set; }
        public string LU_PODRAZD { get; set; }
        public string LU_DOLZHNOST { get; set; }
        public Nullable<decimal> LU_OKLAD { get; set; }
        public double LU_KOEF_RAI { get; set; }
        public double LU_KOEF_VRED { get; set; }
        public System.DateTime LU_PRIEM_DATE { get; set; }
        public Nullable<int> LU_STAZH_CORP_DNEY { get; set; }
        public Nullable<System.DateTime> LU_STAZH_CORP_FIX_DATE { get; set; }
        public Nullable<int> LU_STAZH_MINISTR_DNEY { get; set; }
        public Nullable<System.DateTime> LU_STAZH_MINISTR_FIX_DATE { get; set; }
        public Nullable<System.DateTime> LU_NPF_IN_DATE { get; set; }
        public Nullable<System.DateTime> LU_PENS_DATE { get; set; }
        public System.DateTime LU_BIRTH_DATE { get; set; }
        public string LU_PSP_NAME { get; set; }
        public string LU_PSP_SERIA { get; set; }
        public string LU_PSP_NUM { get; set; }
        public System.DateTime LU_PSP_DATE { get; set; }
        public string LU_PSP_VIDAN { get; set; }
        public string LU_ADDR_HOME_INDEX { get; set; }
        public string LU_ADD_HOME { get; set; }
        public string LU_HOME_PHONE { get; set; }
        public Nullable<System.DateTime> LU_OUT_DATE { get; set; }
        public Nullable<short> LU_OUT_STATIA { get; set; }
        public Nullable<short> LU_OUT_PUNKT { get; set; }
        public string LU_OUT_NAME { get; set; }
        public string LU_PRIZNAK { get; set; }
        public Nullable<short> LU_PEREDANO { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public Nullable<System.DateTime> EDIT_DATE { get; set; }
        public Nullable<short> LU_NAME_LAST_EDITED { get; set; }
        public Nullable<System.DateTime> LU_SVID_DATE { get; set; }
        public Nullable<int> LU_SVID_NUM { get; set; }
        public string LU_SVID_OTV_LITSO { get; set; }
        public Nullable<int> LU_OUT_PRIKAZ_NUM { get; set; }
        public Nullable<System.DateTime> LU_OUT_PRIKAZ_DATE { get; set; }
        public Nullable<short> LU_ZAYAV_PENS_FLAG { get; set; }
        public Nullable<System.DateTime> LU_ZAYAV_PENS_DATE { get; set; }
        public Nullable<short> LU_ERROR_CODE { get; set; }
        public string LU_ERROR_TEXT { get; set; }
        public Nullable<System.DateTime> LU_PEREDANO_DATE { get; set; }
    
        public virtual SD_2 SD_2 { get; set; }
        public virtual SD_314 SD_314 { get; set; }
    }
}
