//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_46
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_46()
        {
            this.SD_212 = new HashSet<SD_212>();
            this.SD_289 = new HashSet<SD_289>();
            this.TD_46 = new HashSet<TD_46>();
            this.UD_46 = new HashSet<UD_46>();
        }
    
        public decimal DOC_CODE { get; set; }
        public short DELETED { get; set; }
        public short IS_ACTIVE { get; set; }
        public Nullable<decimal> MIN_SALARY { get; set; }
        public string NOTES { get; set; }
        public Nullable<System.DateTime> USED_FROM { get; set; }
        public Nullable<short> NU_NUM_ADD { get; set; }
        public Nullable<short> NU_NUM_SUB { get; set; }
        public Nullable<short> NU_NUM_CASH { get; set; }
        public Nullable<short> NU_NUM_SOV_DOHOD { get; set; }
        public Nullable<short> NU_NUM_DUTYFREE { get; set; }
        public Nullable<short> NU_NUM_NALOGOOBLAG { get; set; }
        public Nullable<short> NU_NUM_NALOGY { get; set; }
        public Nullable<short> NU_NUM_NON_USED_DUTYFREE { get; set; }
        public Nullable<short> NU_NUM_DOLGI { get; set; }
        public Nullable<short> NU_NUM_PODOHODNIY { get; set; }
        public Nullable<short> NU_NUM_NALOGOOBLAG_RKSK { get; set; }
        public Nullable<short> NU_NUM_PODOHODNIY_RKSK { get; set; }
        public Nullable<short> NU_NUM_MAT_POM_12_MROT { get; set; }
        public Nullable<short> NU_NUM_LGOT_DLIA_SETKI { get; set; }
        public Nullable<short> NU_NUM_LGOT_BEZ_SETKI { get; set; }
        public Nullable<short> NU_NUM_NALOOBLAG_OSN_BEZ_LG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_212> SD_212 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_289> SD_289 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_46> TD_46 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UD_46> UD_46 { get; set; }
    }
}
