//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_800
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_800()
        {
            this.TD_800 = new HashSet<TD_800>();
            this.UD_800 = new HashSet<UD_800>();
        }
    
        public decimal DOC_CODE { get; set; }
        public System.DateTime TNN_DATE_START { get; set; }
        public Nullable<System.DateTime> TNN_DATE_WHEN { get; set; }
        public Nullable<System.DateTime> TNN_DATE_IN { get; set; }
        public Nullable<decimal> TNN_KONTR_FROM_POINT_DC { get; set; }
        public Nullable<decimal> TNN_KONTR_TO_POINT_DC { get; set; }
        public Nullable<decimal> TNN_SKLAD_FROM_DC { get; set; }
        public Nullable<decimal> TNN_SKLAD_TO_DC { get; set; }
        public decimal TNN_TRANSPORT_DC { get; set; }
        public int TNN_OTVETSTVENNYI_TN { get; set; }
        public decimal TNN_MAIN_PERVOZCHIK_DC { get; set; }
        public string NOTES { get; set; }
    
        public virtual SD_27 SD_27 { get; set; }
        public virtual SD_27 SD_271 { get; set; }
        public virtual SD_43 SD_43 { get; set; }
        public virtual SD_43 SD_431 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_800> TD_800 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UD_800> UD_800 { get; set; }
    }
}
