//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_118
    {
        public int PODP_ID { get; set; }
        public string USERNICKNAME { get; set; }
    
        public virtual SD_118 SD_118 { get; set; }
    }
}
