//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_193
    {
        public decimal NOM_DC { get; set; }
        public Nullable<decimal> CRS_CENA { get; set; }
        public System.DateTime CRS_DATE { get; set; }
        public string VID_RASCH { get; set; }
        public Nullable<short> MANUAL { get; set; }
        public string WHO_SET_MANUAL { get; set; }
        public Nullable<decimal> MAX_CENA_PROD { get; set; }
    
        public virtual SD_83 SD_83 { get; set; }
    }
}
