//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_173
    {
        public decimal DOC_CODE { get; set; }
        public int CODE { get; set; }
        public decimal SGT_NOMENKL_DC { get; set; }
        public decimal SGT_REESTR_DC { get; set; }
        public Nullable<decimal> SGT_NOM_CRS_CENA { get; set; }
        public Nullable<decimal> SGT_UCH_CRS_CENA { get; set; }
        public Nullable<decimal> SGT_KONTR_CRS_CENA { get; set; }
        public double SGT_UCH_CRS_RATE { get; set; }
        public double SGT_KONTR_CRS_RATE { get; set; }
        public decimal SGT_NOM_CRS_DC { get; set; }
    
        public virtual SD_170 SD_170 { get; set; }
        public virtual SD_173 SD_173 { get; set; }
        public virtual SD_301 SD_301 { get; set; }
        public virtual SD_83 SD_83 { get; set; }
    }
}
