//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_302
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TD_302()
        {
            this.UD_281 = new HashSet<UD_281>();
        }
    
        public int CODE { get; set; }
        public decimal DOC_CODE { get; set; }
        public int TABELNUMBER { get; set; }
        public decimal PERT_SUMMA { get; set; }
        public string PERT_RASH_ACC { get; set; }
        public string PERT_NOTES { get; set; }
        public Nullable<decimal> PERT_SUMMA_V_UCHET_VALUTE { get; set; }
        public Nullable<decimal> PERT_RUB_SUMMA { get; set; }
    
        public virtual SD_2 SD_2 { get; set; }
        public virtual SD_302 SD_302 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UD_281> UD_281 { get; set; }
    }
}
