//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_950
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TD_950()
        {
            this.UD_950 = new HashSet<UD_950>();
        }
    
        public decimal DOC_CODE { get; set; }
        public int CODE { get; set; }
        public decimal CNT_NOMENKL_DC { get; set; }
        public double CNT_KOL { get; set; }
        public decimal CNT_PRICE { get; set; }
        public decimal CNT_SUMMA { get; set; }
        public Nullable<decimal> CNT_SF_DC { get; set; }
        public Nullable<int> CNT_SF_ROW_CODE { get; set; }
        public decimal CNT_NOM_CRS_SUMMA { get; set; }
        public double CNT_NOM_CRS_RATE { get; set; }
        public byte[] TSTAMP { get; set; }
    
        public virtual SD_83 SD_83 { get; set; }
        public virtual SD_950 SD_950 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UD_950> UD_950 { get; set; }
    }
}
