//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UD_193
    {
        public decimal DOC_CODE { get; set; }
        public int CODE { get; set; }
        public decimal PRLU_KATEG_DC { get; set; }
        public decimal PRLU_NOMENKL_DC { get; set; }
        public string PRLU_NOMENKL_NAME { get; set; }
        public string PRLU_NOMENKL_NUM { get; set; }
        public string PRLU_NOMENKL_HARACT { get; set; }
        public decimal PRLU_SALE_VAL_DC { get; set; }
        public Nullable<decimal> PRLU_SALE_VAL_KURS_REL_PRICE { get; set; }
        public Nullable<decimal> PRLU_SALE_CRS_NOM_KOMP { get; set; }
        public Nullable<decimal> PRLU_SALE_CRS_NOM_ROZN { get; set; }
        public Nullable<decimal> PRLU_SALE_CRS_PRICE_KOMP { get; set; }
        public Nullable<decimal> PRLU_SALE_CRS_PRICE_ROZN { get; set; }
    
        public virtual SD_148 SD_148 { get; set; }
        public virtual SD_301 SD_301 { get; set; }
        public virtual SD_83 SD_83 { get; set; }
    }
}
