//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UD_2
    {
        public int CODE { get; set; }
        public decimal DOC_CODE { get; set; }
        public Nullable<decimal> STZH_DOC_CODE { get; set; }
        public Nullable<short> PC_SHAZH_YEARS { get; set; }
        public Nullable<short> PC_STAZH_MONTHS { get; set; }
        public Nullable<short> PC_STAZH_DAYS { get; set; }
        public Nullable<System.DateTime> PC_STAZH_BEGIN { get; set; }
        public int TABELNUMBER { get; set; }
        public Nullable<int> PC_STAZH_DAYSALL { get; set; }
    
        public virtual SD_2 SD_2 { get; set; }
        public virtual SD_208 SD_208 { get; set; }
    }
}
