//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UD_83
    {
        public decimal DOC_CODE { get; set; }
        public decimal CODE { get; set; }
        public decimal NOMU_TYPE_DC { get; set; }
        public double NOMU_KOL { get; set; }
        public int NOMU_OBYAZAT_VKLUCH { get; set; }
        public Nullable<decimal> NOMU_INCL_MATER_DC { get; set; }
        public Nullable<decimal> NOMU_SHPZ_APGP_DC { get; set; }
    
        public virtual SD_119 SD_119 { get; set; }
        public virtual SD_303 SD_303 { get; set; }
        public virtual SD_83 SD_83 { get; set; }
        public virtual SD_83 SD_831 { get; set; }
    }
}
