//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UD_903
    {
        public decimal DOC_CODE { get; set; }
        public decimal NUU_CRS_DC { get; set; }
        public Nullable<decimal> NUU_CRS_RATE { get; set; }
    
        public virtual SD_301 SD_301 { get; set; }
        public virtual SD_903 SD_903 { get; set; }
    }
}
