//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VD_27
    {
        public decimal DOC_CODE { get; set; }
        public decimal SKLV_PERIOD_DC { get; set; }
        public decimal SKLV_NOMENKL_DC { get; set; }
        public System.DateTime SKLV_POST_DATE { get; set; }
        public short SKLV_FLAG { get; set; }
        public double SKLV_IN_KOL { get; set; }
        public decimal SKLV_CENA { get; set; }
    
        public virtual UD_27 UD_27 { get; set; }
    }
}
