//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VH_SD_102
    {
        public decimal DOC_CODE { get; set; }
        public string TD_NAME { get; set; }
        public short TD_0BUY_1SALE { get; set; }
        public Nullable<short> TD_DOP_SOGL { get; set; }
        public Nullable<short> TD_DILER { get; set; }
    }
}
