//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WD_116
    {
        public int AMW_CODE { get; set; }
        public int AMW_VIR_ID { get; set; }
        public double AMW_PERCENT { get; set; }
    
        public virtual TD_116 TD_116 { get; set; }
        public virtual VD_116 VD_116 { get; set; }
    }
}
