//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class XD_152
    {
        public decimal DOC_CODE { get; set; }
        public int CODE { get; set; }
        public short M_MONTH { get; set; }
        public short M_YEAR { get; set; }
        public short M_BALANS { get; set; }
    
        public virtual SD_152 SD_152 { get; set; }
    }
}
