//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class XD_207
    {
        public decimal DOC_CODE { get; set; }
        public int CODE { get; set; }
        public int VNX_ROW_CODE { get; set; }
        public short VNX_NACH_CODE { get; set; }
        public short VNX_FLAG_RUCH_VVOD { get; set; }
        public double VNX_SUMM { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime VNX_RED_DATE { get; set; }
    
        public virtual SD_207 SD_207 { get; set; }
        public virtual TD_207 TD_207 { get; set; }
        public virtual UD_197 UD_197 { get; set; }
    }
}
