//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMediaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class YD_207
    {
        public Nullable<decimal> DOC_CODE { get; set; }
        public int VNY_NACH_ROW_CODE { get; set; }
        public int CODE { get; set; }
        public System.DateTime VNY_MONTH { get; set; }
        public Nullable<decimal> VNY_MONTH_SUM { get; set; }
        public Nullable<double> VNY_MONTH_HOURS { get; set; }
        public Nullable<decimal> VNY_HOUR_AVER { get; set; }
        public Nullable<short> VNY_RUCH_VVOD { get; set; }
        public string VNY_RUCH_VVOD_CREATOR { get; set; }
        public Nullable<System.DateTime> VNY_RUCH_VVOD_DATE { get; set; }
        public Nullable<double> VNY_PROCENT_INDEX { get; set; }
    
        public virtual SD_207 SD_207 { get; set; }
        public virtual TD_207 TD_207 { get; set; }
    }
}
