using System;
using System.Windows;
using System.Windows.Media.Imaging;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.LayoutControl;
using Helper;
using KursRepozit.ViewModels;

namespace KursRepozit.Views
{
    /// <summary>
    ///     Interaction logic for UserFormView.xaml
    /// </summary>
    public partial class UserFormView
    {
        public UserFormView()
        {
            InitializeComponent();
        }

        private void LayoutItems_OnAutoGeneratingItem(object sender, DataLayoutControlAutoGeneratingItemEventArgs e)
        {
            var doc = DataContext as UserFormViewModel;
            if (doc == null) return;
            var oldContent = e.Item.Content as BaseEdit;
            if (e.PropertyName.Contains("Command"))
            {
                e.Item.Visibility = Visibility.Hidden;
                return;
            }

            switch (e.PropertyName)
            {
                case nameof(UserFormViewModel.AvatarSource):
                    var newContent = new ImageEdit();
                    newContent.Height = 250;
                    newContent.Width = 250;
                    newContent.EditValuePostMode = PostMode.Immediate;
                    newContent.EditValueChanged += NewContent_EditValueChanged;
                    BindingHelper.CopyBinding(oldContent, newContent, BaseEdit.EditValueProperty);
                    e.Item.Content = newContent;
                    break;
            }

            ViewFluentHelper.SetModeUpdateProperties(doc, e.Item, e.PropertyName);
        }

        private void NewContent_EditValueChanged(object sender, EditValueChangedEventArgs e)
        {
            if (DataContext is UserFormViewModel vm) vm.AvatarSource = (BitmapImage) e.NewValue;
        }

        private void LayoutItems_OnAutoGeneratedUI(object sender, EventArgs e)
        {
        }
    }
}