using System.Windows;
using Core.EntityViewModel.CommonReferences;
using DevExpress.Xpf.Core;
using DevExpress.Xpf.Grid;
using KursAM2.ViewModel.Reference;
using KursDomain.Documents.CommonReferences;
using KursDomain.References;

namespace KursAM2.View.KursReferences.UC
{
    /// <summary>
    ///     Interaction logic for CurrencyReferenceUC.xaml
    /// </summary>
    public partial class CurrencyReferenceUC
    {
        public CurrencyReferenceUC()
        {
            InitializeComponent();
            ApplicationThemeHelper.ApplicationThemeName = Theme.MetropolisLightName;
        }

        private void GridControl_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
        }

        private void GridControl_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
        }

        private void tableView_CellValueChanged(object sender, CellValueChangedEventArgs e)
        {
            if (e.Column.FieldName == "IsMain")
                if (DataContext is CurrencyReferenceWindowViewModel dtx)
                    foreach (var c in dtx.CurrencyCollection)
                        if (((CurrencyViewModel) e.Row).Id != c.Id)
                            c.IsMain = false;
        }
    }
}
