using KursDomain.ICommon;
using KursDomain.IReferences;
using System.Collections.Generic;
using System.Diagnostics;
using Data;
using Core.Helper;
using Core.ViewModel.Base;
using DevExpress.Mvvm.DataAnnotations;
using System.ComponentModel.DataAnnotations;
using System;

namespace KursDomain.References;
[DebuggerDisplay("{DocCode,nq}/{Id} {Name,nq}")]
public class SDRSchet :  ISDRSchet, IDocCode,  IName, IEqualityComparer<IDocCode>
{
    [Display(AutoGenerateField = true,Name = "Удален")]
    public bool IsDeleted { get; set; }
    [Display(AutoGenerateField = true,Name = "Статья")]
    public ISDRState SDRState { get; set; }
    [Display(AutoGenerateField = true,Name = "Под отчет")]
    public bool IsPodOtchet { get; set; }
    [Display(AutoGenerateField = true,Name = "Зарплата")]
    public bool IsEmployeePayment { get; set; }
    [Display(AutoGenerateField = false,Name = "DocCode")]
    public decimal DocCode { get; set; }
    [Display(AutoGenerateField = true,Name = "Наименование")]
    public string Name { get; set; }
    [Display(AutoGenerateField = true,Name = "Примечание")]
    public string Notes { get; set; }
    [Display(AutoGenerateField = false,Name = "Описание")]
    public string Description => $"Счет дох/расх: {Name}";
    public override string ToString()
    {
        return Name;
    }

    public void LoadFromEntity(SD_303 entity, IReferencesCache refCache)
    {
        if (entity == null)
        {
            DocCode = -1;
            return;
        }

        DocCode = entity.DOC_CODE;
        IsDeleted = entity.SHPZ_DELETED == 1;
        SDRState = refCache?.GetSDRState(entity.SHPZ_STATIA_DC);
        IsPodOtchet = entity.SHPZ_PODOTCHET == 1;
        IsEmployeePayment = entity.SHPZ_1ZARPLATA_0NO == 1;
        Name = entity.SHPZ_NAME;
    }

    public bool Equals(IDocCode x, IDocCode y)
    {
        if (ReferenceEquals(x, y)) return true;
        if (ReferenceEquals(x, null)) return false;
        if (ReferenceEquals(y, null)) return false;
        if (x.GetType() != y.GetType()) return false;
        return x.DocCode == y.DocCode;
    }

    public int GetHashCode(IDocCode obj)
    {
        return obj.DocCode.GetHashCode();
    }
}

/// <summary>
///     Счет доходов и расходов
/// </summary>
// ReSharper disable once InconsistentNaming
[MetadataType(typeof(DataAnnotationsSDRSchet))]
public class SDRSchetViewModel : RSViewModelBase, IEntity<SD_303>
{
    private SD_303 myEntity;


    private string mySHPZ_SHIRF;

    public SDRSchetViewModel()
    {
        Entity = DefaultValue();
    }

    public SDRSchetViewModel(SD_303 entity)
    {
        Entity = entity ?? new SD_303 { DOC_CODE = -1 };
    }

    public new string Name
    {
        get => Entity.SHPZ_NAME;
        set
        {
            if (Entity.SHPZ_NAME == value) return;
            Entity.SHPZ_NAME = value;
            RaisePropertyChanged();
        }
    }

    public string SHPZ_SHIRF
    {
        get => mySHPZ_SHIRF;
        set
        {
            if (mySHPZ_SHIRF == value) return;
            mySHPZ_SHIRF = value;
            RaisePropertyChanged();
        }
    }

    public override decimal DocCode
    {
        get => Entity.DOC_CODE;
        set
        {
            if (Entity.DOC_CODE == value) return;
            Entity.DOC_CODE = value;
            RaisePropertyChanged();
        }
    }

    public decimal? SHPZ_STATIA_DC
    {
        get => Entity.SHPZ_STATIA_DC;
        set
        {
            if (Entity.SHPZ_STATIA_DC == value) return;
            Entity.SHPZ_STATIA_DC = value;
            RaisePropertyChanged();
        }
    }

    public bool IsAccessRight { get; set; }

    public SD_303 DefaultValue()
    {
        return new SD_303 { DOC_CODE = -1 };
    }

    public SD_303 Entity
    {
        get => myEntity;
        set
        {
            if (myEntity == value) return;
            myEntity = value;
            RaisePropertyChanged();
        }
    }

    public List<SD_303> LoadList()
    {
        throw new NotImplementedException();
    }

    public override string ToString()
    {
        return Name;
    }
}

public class DataAnnotationsSDRSchet : DataAnnotationForFluentApiBase, IMetadataProvider<SDRSchetViewModel>
{
    void IMetadataProvider<SDRSchetViewModel>.BuildMetadata(MetadataBuilder<SDRSchetViewModel> builder)
    {
        SetNotAutoGenerated(builder);

        //builder.Property(_ => _.Entity).NotAutoGenerated();
        builder.Property(_ => _.Name).AutoGenerated().DisplayName("Наименование").Required();
        builder.Property(_ => _.SHPZ_SHIRF).AutoGenerated().DisplayName("Шифр").Required();
    }
}
