using System.Windows;
using DevExpress.Data;
using DevExpress.Xpf.Grid;

namespace KursAM2.View.Finance.AccruedAmount
{
    /// <summary>
    ///     Interaction logic for AccruedAmountOfSupplierSearchView.xaml
    /// </summary>
    public partial class AccruedAmountOfSupplierSearchView 
    {
        public AccruedAmountOfSupplierSearchView()
        {
            InitializeComponent();
        }

        private void RowsControl_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            resultGridControl.TotalSummary.Add(new GridSummaryItem
            {
                FieldName = "Summa",
                SummaryType = SummaryItemType.Sum,
                DisplayFormat = "n2"
            });
            resultGridControl.TotalSummary.Add(new GridSummaryItem
            {
                FieldName = "DocInNum",
                SummaryType = SummaryItemType.Count,
                DisplayFormat = "n0"
            });
        }

        private void RowsControl_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
            e.Column.ReadOnly = true;
        }
    }
}