using System.Collections.Generic;
using System.Linq;
using System.Windows;
using Core;
using Data;
using DevExpress.Data;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Grid;
using KursAM2.View.KursReferences;
using KursAM2.ViewModel.Reference;

namespace KursAM2.View.Finance.AccruedAmount
{
    /// <summary>
    ///     Interaction logic for AccruedAmountForClientView.xaml
    /// </summary>
    public partial class AccruedAmountForClientView
    {
        private ComboBoxEditSettings typeEdit;
        public AccruedAmountForClientView()
        {
            InitializeComponent();
        }

        private void GridRows_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
            switch (e.Column.FieldName)
            {
                case "Summa":
                    e.Column.EditSettings = new CalcEditSettings
                    {
                        DisplayFormat = "n2",
                        MaskUseAsDisplayFormat = true
                    };
                    break;
                case "AccruedAmountType":
                    typeEdit = new ComboBoxEditSettings
                    {
                        Name = "PART_Editor",
                        TextWrapping = TextWrapping.Wrap,
                        IsTextEditable = false,
                        AutoComplete = true,
                    };
                    typeEdit.DefaultButtonClick += TypeEdit_DefaultButtonClick;
                    var bn = new ButtonInfo
                    {
                        GlyphKind = GlyphKind.Edit
                    };
                    bn.Click += Bn_Click;
                    typeEdit.Buttons.Add(bn);
                    e.Column.EditSettings = typeEdit;
                    break;
            }
        }

        private void TypeEdit_DefaultButtonClick(object sender, RoutedEventArgs e)
        {
            typeEdit.ItemsSource = MainReferences.GetAllAccruedAmountType();
        }

        private void Bn_Click(object sender, RoutedEventArgs e)
        {
            var aat = new AccruedAmountTypeWindowViewModel();
            var form = new AccruedAmountTypeView
            {
                Owner = Application.Current.MainWindow,
                DataContext = aat
            };
            aat.Form = form;
            form.Show();
        }

        private void GridRows_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            gridRows.TotalSummary.Add(new GridSummaryItem
            {
                FieldName = "Summa",
                SummaryType = SummaryItemType.Sum,
                DisplayFormat = "n2"
            });
        }

        private void TableViewRows_OnCellValueChanging(object sender, CellValueChangedEventArgs e)
        {
            //gridRows.UpdateTotalSummary();
        }

        private void TableViewRows_OnCellValueChanged(object sender, CellValueChangedEventArgs e)
        {
            gridRows.UpdateTotalSummary();
        }
    }
}