using System.Windows;
using DevExpress.Xpf.Core;
using DevExpress.Xpf.Grid;

namespace KursAM2.View.Shop
{
    /// <summary>
    ///     Interaction logic for ShopParserExtFiles.xaml
    /// </summary>
    public partial class ShopParserExtFiles
    {
        public ShopParserExtFiles()
        {
            InitializeComponent(); 
            
        }

        private void DataControlBase_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            
        }

        private void DataControlBase_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            
        }
    }
}
