//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccuredAmountForClientRow
    {
        public System.Guid Id { get; set; }
        public System.Guid DocId { get; set; }
        public System.Guid AccuredAmountTypeId { get; set; }
        public decimal Summa { get; set; }
        public string Note { get; set; }
    
        public virtual AccruedAmountForClient AccruedAmountForClient { get; set; }
        public virtual AccruedAmountType AccruedAmountType { get; set; }
    }
}
