//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankPeriodsOperations
    {
        public decimal BankDC { get; set; }
        public System.DateTime Date { get; set; }
        public decimal CrsDC { get; set; }
        public Nullable<decimal> SummaStart { get; set; }
        public Nullable<decimal> SummaIn { get; set; }
        public Nullable<decimal> SummaOut { get; set; }
        public Nullable<decimal> SummaEnd { get; set; }
    }
}
