//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASH_CORR
    {
        public System.DateTime CASH_DATE { get; set; }
        public System.Guid Id { get; set; }
        public string CORR_SUMMA { get; set; }
    }
}
