//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CD_2
    {
        public int TABELNUMBER { get; set; }
        public int CODE { get; set; }
        public decimal CONST_DC { get; set; }
        public Nullable<System.DateTime> MONTH_FROM { get; set; }
        public Nullable<System.DateTime> MONTH_TO { get; set; }
    
        public virtual SD_2 SD_2 { get; set; }
        public virtual SD_31 SD_31 { get; set; }
    }
}
