//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientServiceActRow
    {
        public System.Guid Id { get; set; }
        public System.Guid DocId { get; set; }
        public decimal InvoiceDC { get; set; }
        public int InvoiceRowCode { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<System.DateTime> DateFact { get; set; }
        public string Note { get; set; }
    
        public virtual ClientServiceAct ClientServiceAct { get; set; }
        public virtual TD_84 TD_84 { get; set; }
    }
}
