//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CROSS_ZH7
    {
        public System.DateTime av_period_start { get; set; }
        public System.DateTime av_period_stop { get; set; }
        public int AV_TN { get; set; }
        public string AV_NAME { get; set; }
        public Nullable<decimal> AV_IN_DEB { get; set; }
        public Nullable<decimal> AV_IN_CRED { get; set; }
        public Nullable<decimal> AV_OB_VIDANO { get; set; }
        public Nullable<decimal> AV_OB_CONFIRM { get; set; }
        public Nullable<decimal> AV_IN_RETURN { get; set; }
        public Nullable<decimal> AV_OUT_DEB { get; set; }
        public Nullable<decimal> AV_OUT_CRED { get; set; }
        public string AV_HEADER { get; set; }
        public Nullable<decimal> AV_VALUE { get; set; }
        public Nullable<short> AN_1PRI_0RAS { get; set; }
    }
}
