//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributeNakladInfo
    {
        public System.Guid Id { get; set; }
        public System.Guid RowId { get; set; }
        public System.Guid InvoiceNakladId { get; set; }
        public decimal InvoiceCrsDC { get; set; }
        public decimal Rate { get; set; }
        public decimal DistributeSumma { get; set; }
        public Nullable<decimal> NakladSumma { get; set; }
    
        public virtual SD_301 SD_301 { get; set; }
        public virtual DistributeNakladRow DistributeNakladRow { get; set; }
    }
}
