//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DogovorOfSupplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DogovorOfSupplier()
        {
            this.DogovorOfSupplierRow = new HashSet<DogovorOfSupplierRow>();
            this.SD_26 = new HashSet<SD_26>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime DocDate { get; set; }
        public int InNum { get; set; }
        public string OutNum { get; set; }
        public decimal KontrDC { get; set; }
        public string Creator { get; set; }
        public bool IsClosed { get; set; }
        public string Note { get; set; }
        public int OtvetstvenTN { get; set; }
        public decimal DogType { get; set; }
        public Nullable<bool> IsNDSInPrice { get; set; }
    
        public virtual SD_102 SD_102 { get; set; }
        public virtual SD_43 SD_43 { get; set; }
        public virtual SD_2 SD_2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DogovorOfSupplierRow> DogovorOfSupplierRow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_26> SD_26 { get; set; }
    }
}
