//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Errors
    {
        public System.Guid Id { get; set; }
        public System.Guid DbId { get; set; }
        public System.Guid UserId { get; set; }
        public string Host { get; set; }
        public string ErrorText { get; set; }
        public string Note { get; set; }
    
        public virtual DataSources DataSources { get; set; }
        public virtual Users Users { get; set; }
    }
}
