//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXT_ARM_STATION_REFRESH
    {
        public int REFR_ID { get; set; }
        public string REFR_WORKSTATION { get; set; }
        public int ARM_ID { get; set; }
        public string REFR_BY_USER { get; set; }
        public System.DateTime REF_TIME { get; set; }
    }
}
