//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXT_DOCPAGES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXT_DOCPAGES()
        {
            this.EXT_DOCOBJ = new HashSet<EXT_DOCOBJ>();
        }
    
        public int DP_ID { get; set; }
        public int TABLE_CODE { get; set; }
        public string DP_NAME { get; set; }
        public double DP_PARENT { get; set; }
        public string DP_VARNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_DOCOBJ> EXT_DOCOBJ { get; set; }
    }
}
