//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXT_DLG
    {
        public int DLG_ID { get; set; }
        public string DLG_NAME { get; set; }
        public string DLG_NOTES { get; set; }
        public string DLG_IN_PARAMS { get; set; }
        public string DLG_OUT_PARAM { get; set; }
        public short DLG_MULTIPLE_SELECT { get; set; }
    }
}
