//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KursMenuItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KursMenuItem()
        {
            this.FormLayout = new HashSet<FormLayout>();
            this.LastMenuUserSearch = new HashSet<LastMenuUserSearch>();
            this.SignatureSchemes = new HashSet<SignatureSchemes>();
            this.UserMenuFavorites = new HashSet<UserMenuFavorites>();
            this.UserMenuRight = new HashSet<UserMenuRight>();
            this.UserRoles = new HashSet<UserRoles>();
        }
    
        public int Id { get; set; }
        public int GroupId { get; set; }
        public string Name { get; set; }
        public byte[] Picture { get; set; }
        public string Note { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string Code { get; set; }
        public bool IsSign { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormLayout> FormLayout { get; set; }
        public virtual KursMenuGroup KursMenuGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LastMenuUserSearch> LastMenuUserSearch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SignatureSchemes> SignatureSchemes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMenuFavorites> UserMenuFavorites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMenuRight> UserMenuRight { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRoles> UserRoles { get; set; }
    }
}
