//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Core.EntityClient;
using System.Data.SqlClient;

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class KursSystemEntities : DbContext
    {
        public KursSystemEntities()
            : base(new EntityConnectionStringBuilder
            {
                Provider = "System.Data.SqlClient",
                ProviderConnectionString = new SqlConnectionStringBuilder
                {
                    DataSource = "172.16.0.1",
                    InitialCatalog = "KursSystem",
                    UserID = "sa",
                    Password = "CbvrfFhntvrf65"
                }.ToString(),
                Metadata =
                @"res://*/KursSystem.csdl|res://*/KursSystem.ssdl|res://*/KursSystem.msl"
            }.ToString())
        {
            Configuration.ValidateOnSaveEnabled = true;
            Configuration.LazyLoadingEnabled = false;
            Configuration.AutoDetectChangesEnabled = true;
        }


        public KursSystemEntities(string connectionString,
                    bool validationMode = true,
                    bool lazyLoadingMode = true,
                    bool autoDetectMode = true)
                    : base(new EntityConnectionStringBuilder
                    {
                        Provider = "System.Data.SqlClient",
                        ProviderConnectionString = connectionString,
                        Metadata =
                            @"res://*/KursSystem.csdl|res://*/KursSystem.ssdl|res://*/KursSystem.msl"
                    }.ToString())
        {
            Configuration.ValidateOnSaveEnabled = validationMode;
            Configuration.LazyLoadingEnabled = lazyLoadingMode;
            Configuration.AutoDetectChangesEnabled = autoDetectMode;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DataSources> DataSources { get; set; }
        public virtual DbSet<KontragentCashes> KontragentCashes { get; set; }
        public virtual DbSet<KursMenuGroup> KursMenuGroup { get; set; }
        public virtual DbSet<KursMenuItem> KursMenuItem { get; set; }
        public virtual DbSet<UserMenuRight> UserMenuRight { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Version> Version { get; set; }
        public virtual DbSet<VersionInfo> VersionInfo { get; set; }
        public virtual DbSet<Errors> Errors { get; set; }
        public virtual DbSet<FormLayout> FormLayout { get; set; }
        public virtual DbSet<UserMenuOrder> UserMenuOrder { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<TasksLog> TasksLog { get; set; }
    }
}
