//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ND_43
    {
        public decimal DOC_CODE { get; set; }
        public decimal BALANS_DC { get; set; }
        public decimal ACC_DC { get; set; }
    
        public virtual SD_108 SD_108 { get; set; }
        public virtual SD_43 SD_43 { get; set; }
        public virtual SD_298 SD_298 { get; set; }
    }
}
