//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOMENKL_MOVES
    {
        public System.Guid Id { get; set; }
        public System.DateTime OperDate { get; set; }
        public System.Guid NomenklId { get; set; }
        public Nullable<System.Guid> SkladInId { get; set; }
        public Nullable<System.Guid> SkladOutId { get; set; }
        public System.Guid CurrencyId { get; set; }
        public decimal QuantityIn { get; set; }
        public decimal QuantityOut { get; set; }
        public decimal SummaIn { get; set; }
        public decimal SummaOut { get; set; }
        public string Note { get; set; }
        public Nullable<System.Guid> DocId { get; set; }
        public Nullable<decimal> Type { get; set; }
    }
}
