//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NomenklCostResetRows
    {
        public System.Guid Id { get; set; }
        public System.Guid DocId { get; set; }
        public System.Guid NomenklId { get; set; }
        public System.Guid CurrencyId { get; set; }
        public decimal Quantity { get; set; }
        public System.Guid CurrencyNewId { get; set; }
        public decimal QuantityReset { get; set; }
        public decimal Rate { get; set; }
        public string Note { get; set; }
    
        public virtual NomenklCostReset NomenklCostReset { get; set; }
    }
}
