//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NomenklMoveStore
    {
        public decimal NomDC { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> StoreDC { get; set; }
        public Nullable<decimal> Prihod { get; set; }
        public Nullable<decimal> Rashod { get; set; }
        public Nullable<decimal> Nakopit { get; set; }
        public Nullable<decimal> SummaIn { get; set; }
        public Nullable<decimal> SummaNakladIn { get; set; }
        public Nullable<decimal> SummaOut { get; set; }
        public Nullable<decimal> SummaNakladOut { get; set; }
        public decimal Price { get; set; }
        public decimal PriceWithNaklad { get; set; }
    }
}
