//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NomenklReturnOfClient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NomenklReturnOfClient()
        {
            this.NomenklReturnOfClientRow = new HashSet<NomenklReturnOfClientRow>();
        }
    
        public System.Guid Id { get; set; }
        public int DocNum { get; set; }
        public string DocExtNum { get; set; }
        public System.DateTime DocDate { get; set; }
        public decimal KontragentDC { get; set; }
        public Nullable<decimal> InvoiceClientDC { get; set; }
        public string Note { get; set; }
    
        public virtual SD_84 SD_84 { get; set; }
        public virtual SD_43 SD_43 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NomenklReturnOfClientRow> NomenklReturnOfClientRow { get; set; }
    }
}
