//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OffBalanceSheetInDoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OffBalanceSheetInDoc()
        {
            this.OffBalanceSheetInRow = new HashSet<OffBalanceSheetInRow>();
        }
    
        public System.Guid Id { get; set; }
        public string Num { get; set; }
        public decimal KontrDC { get; set; }
        public string Note { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid TypeDocId { get; set; }
    
        public virtual OffBalanceSheetChargesType OffBalanceSheetChargesType { get; set; }
        public virtual SD_43 SD_43 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OffBalanceSheetInRow> OffBalanceSheetInRow { get; set; }
    }
}
