//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectsDocs
    {
        public System.Guid Id { get; set; }
        public System.Guid ProjectId { get; set; }
        public string DocTypeName { get; set; }
        public string DocInfo { get; set; }
        public string Note { get; set; }
        public decimal DocDC { get; set; }
        public Nullable<int> DocRowId { get; set; }
        public Nullable<decimal> FactCrsDC { get; set; }
        public Nullable<decimal> FactCRSSumma { get; set; }
    
        public virtual Projects Projects { get; set; }
        public virtual SD_301 SD_301 { get; set; }
    }
}
