//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_17
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_17()
        {
            this.SD_122 = new HashSet<SD_122>();
            this.SD_161 = new HashSet<SD_161>();
            this.SD_171 = new HashSet<SD_17>();
            this.SD_187 = new HashSet<SD_187>();
            this.SD_1871 = new HashSet<SD_187>();
            this.TD_17 = new HashSet<TD_17>();
            this.EXT_USERS = new HashSet<EXT_USERS>();
        }
    
        public int IERARHY { get; set; }
        public short IS_REMOVED { get; set; }
        public short DELETED { get; set; }
        public string WORK_NAME { get; set; }
        public byte[] DELETE_DATE { get; set; }
        public string FULL_WORK_NAME { get; set; }
        public short ZASHTATN { get; set; }
        public Nullable<int> IERARHY_PARENT { get; set; }
        public int UPPER_IERARHY { get; set; }
        public Nullable<decimal> NCH_DOC_CODE { get; set; }
        public string DPT_STR_CODE { get; set; }
        public Nullable<decimal> TBT_DC { get; set; }
        public Nullable<double> KOEF_RAI { get; set; }
        public Nullable<decimal> SHPZ_DC { get; set; }
        public Nullable<short> PODRAZD_TYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_122> SD_122 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_161> SD_161 { get; set; }
        public virtual SD_270 SD_270 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_17> SD_171 { get; set; }
        public virtual SD_17 SD_172 { get; set; }
        public virtual SD_303 SD_303 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_187> SD_187 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_187> SD_1871 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_17> TD_17 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_USERS> EXT_USERS { get; set; }
    }
}
