//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_114_Remains
    {
        public System.Guid Id { get; set; }
        public decimal AccountDC { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Start { get; set; }
        public decimal SummaIn { get; set; }
        public decimal SummaOut { get; set; }
        public decimal End { get; set; }
    }
}
