//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_197
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_197()
        {
            this.SD_207 = new HashSet<SD_207>();
            this.TD_197 = new HashSet<TD_197>();
            this.VD_197 = new HashSet<VD_197>();
        }
    
        public decimal DOC_CODE { get; set; }
        public short NCH_DELETED { get; set; }
        public string NCH_NAME { get; set; }
        public string NCH_NOTES { get; set; }
        public string NCH_AVER_ZPL { get; set; }
        public short NCH_CALC_AVER_ZPL { get; set; }
        public short NCH_USE_KTV { get; set; }
        public short NCH_ACTIVE { get; set; }
        public Nullable<short> NCH_USE_COLL_FOND { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_207> SD_207 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_197> TD_197 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VD_197> VD_197 { get; set; }
    }
}
