//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_213
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_213()
        {
            this.SD_215 = new HashSet<SD_215>();
            this.SD_305 = new HashSet<SD_305>();
            this.EXT_USERS = new HashSet<EXT_USERS>();
        }
    
        public decimal DOC_CODE { get; set; }
        public string NT_NAME { get; set; }
        public short NT_DELETED { get; set; }
        public Nullable<int> OP_CODE { get; set; }
        public string NT_FLAG { get; set; }
        public Nullable<short> NT_CALC_BY_PROC { get; set; }
        public string NT_PROCEDURE { get; set; }
        public Nullable<short> NT_BY_VED { get; set; }
        public Nullable<short> NT_NCODE { get; set; }
        public Nullable<short> NT_CALC_MAT_VIGODA { get; set; }
        public Nullable<short> NT_UCH_IN_BOLNICH_CALC { get; set; }
    
        public virtual VD_46 VD_46 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_215> SD_215 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_305> SD_305 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_USERS> EXT_USERS { get; set; }
    }
}
