//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_299
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_299()
        {
            this.SD_312 = new HashSet<SD_312>();
            this.TD_299 = new HashSet<TD_299>();
        }
    
        public decimal DOC_CODE { get; set; }
        public int RPV_NUM { get; set; }
        public System.DateTime RPV_DATE { get; set; }
        public string RPV_WHAT_FOR { get; set; }
        public decimal RPV_SUMMA { get; set; }
        public Nullable<decimal> CODE_CASS { get; set; }
        public Nullable<short> OP_CODE { get; set; }
        public Nullable<decimal> RPV_ZPL_MONTH_DC { get; set; }
        public decimal CA_DC { get; set; }
        public string RPV_SHPZ { get; set; }
        public Nullable<decimal> SHPZ_DC { get; set; }
        public Nullable<short> NCODE { get; set; }
        public Nullable<decimal> TABEL_DC { get; set; }
        public Nullable<decimal> CRS_DC { get; set; }
        public Nullable<decimal> UCH_VALUTA_DC { get; set; }
        public Nullable<decimal> SUMMA_V_UCH_VALUTE { get; set; }
        public Nullable<double> UCH_VALUTA_RATE { get; set; }
        public string CREATOR { get; set; }
        public Nullable<decimal> RPV_RUB_SUMMA { get; set; }
        public Nullable<double> RPV_RUB_RATE { get; set; }
        public Nullable<decimal> RPV_ZPL_VED_DC { get; set; }
    
        public virtual SD_22 SD_22 { get; set; }
        public virtual SD_270 SD_270 { get; set; }
        public virtual SD_289 SD_289 { get; set; }
        public virtual VD_46 VD_46 { get; set; }
        public virtual SD_301 SD_301 { get; set; }
        public virtual SD_39 SD_39 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_312> SD_312 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_299> TD_299 { get; set; }
    }
}
