//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_246
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_246()
        {
            this.TD_246 = new HashSet<TD_246>();
        }
    
        public decimal DOC_CODE { get; set; }
        public System.DateTime SF_DATE { get; set; }
        public int SF_IN_NUM { get; set; }
        public string SF_OUT_NUM { get; set; }
        public decimal SF_POST_DC { get; set; }
        public string SF_POST_GRUZOOTPRAV { get; set; }
        public decimal SF_POLUCH_DC { get; set; }
        public string SF_POLUCH_GRUZOPOLUCH { get; set; }
        public string SF_CREATOR { get; set; }
        public string SF_NOTES { get; set; }
    
        public virtual SD_43 SD_43 { get; set; }
        public virtual SD_43 SD_431 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_246> TD_246 { get; set; }
    }
}
