//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_312
    {
        public decimal DOC_CODE { get; set; }
        public int TABELNUMBER { get; set; }
        public System.DateTime DEP_DATE { get; set; }
        public decimal DEP_SUMMA { get; set; }
        public short DEP_RECEIVED { get; set; }
        public Nullable<decimal> DEP_RAS_ORDER_DC { get; set; }
        public Nullable<decimal> DEP_PLAT_VEDOM_DC { get; set; }
    
        public virtual SD_2 SD_2 { get; set; }
        public virtual SD_299 SD_299 { get; set; }
        public virtual SD_34 SD_34 { get; set; }
    }
}
