//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_379
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_379()
        {
            this.TD_379 = new HashSet<TD_379>();
            this.UD_379 = new HashSet<UD_379>();
        }
    
        public decimal DOC_CODE { get; set; }
        public decimal PPZ_CENTR_OTV_DC { get; set; }
        public decimal PPZ_PERIOD_DC { get; set; }
        public System.DateTime PPZ_START_DATE { get; set; }
        public System.DateTime PPZ_STOP_DATE { get; set; }
        public Nullable<decimal> PPZ_PLAN_REALIZ_SUM { get; set; }
        public Nullable<decimal> PPZ_FACT_REALIZ_SUM { get; set; }
        public Nullable<decimal> PPZ_REALIZ_DELTA { get; set; }
        public Nullable<decimal> PPZ_PLAN_ZAKUP_SUM { get; set; }
        public Nullable<decimal> PPZ_FACT_ZAKUP_SUM { get; set; }
        public Nullable<decimal> PPZ_ZAKUP_DELTA { get; set; }
    
        public virtual SD_138 SD_138 { get; set; }
        public virtual SD_40 SD_40 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_379> TD_379 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UD_379> UD_379 { get; set; }
    }
}
