//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_372
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_372()
        {
            this.TD_372 = new HashSet<TD_372>();
            this.TD_395 = new HashSet<TD_395>();
        }
    
        public decimal DOC_CODE { get; set; }
        public int SF_IN_NUM { get; set; }
        public string SF_OUT_NUM { get; set; }
        public System.DateTime SF_DATE { get; set; }
        public Nullable<System.DateTime> SF_POSTAV_DATE { get; set; }
        public Nullable<System.DateTime> SF_PRIHOD_DATE { get; set; }
        public decimal SF_POSTAV_KONTR_DC { get; set; }
        public decimal SF_POLUCH_KONTR_DC { get; set; }
        public Nullable<decimal> SF_SUMMA_K_OPLATE { get; set; }
        public Nullable<decimal> SF_SUMMA_OPLACHENO { get; set; }
        public Nullable<decimal> SF_SPOST_DC { get; set; }
        public Nullable<System.DateTime> SF_OPLATA_DATE { get; set; }
        public string SF_NOTES { get; set; }
        public Nullable<short> SF_NDS_VKL_V_CENU { get; set; }
        public Nullable<short> SF_AUTO_CREATE { get; set; }
        public string SF_PLAT_DOCUM { get; set; }
    
        public virtual SD_26 SD_26 { get; set; }
        public virtual SD_43 SD_43 { get; set; }
        public virtual SD_43 SD_431 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_372> TD_372 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_395> TD_395 { get; set; }
    }
}
