//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_327
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_327()
        {
            this.TD_327 = new HashSet<TD_327>();
        }
    
        public decimal DOC_CODE { get; set; }
        public int TOV_NUM { get; set; }
        public System.DateTime TOV_DATE { get; set; }
        public int TABELNUMBER { get; set; }
        public Nullable<decimal> TOV_SUMMA { get; set; }
        public decimal TOV_CRS_DC { get; set; }
        public Nullable<decimal> TOV_CRS_SUMMA { get; set; }
        public string CREATOR { get; set; }
        public Nullable<decimal> TOV_PRIH_CASH_ORDER_DC { get; set; }
        public Nullable<decimal> TOV_SHPZ_DC { get; set; }
        public Nullable<decimal> TOV_VZAIMOR_TYPE_DC { get; set; }
        public Nullable<decimal> TOV_DOG_OTGRUZ_DC { get; set; }
        public Nullable<double> TOV_UCH_VALUTA_RATE { get; set; }
        public Nullable<decimal> TOV_UCH_VALUTA_DC { get; set; }
        public Nullable<double> TOV_CRS_RATE { get; set; }
        public Nullable<decimal> TOV_RUB_SUMMA { get; set; }
    
        public virtual SD_2 SD_2 { get; set; }
        public virtual SD_301 SD_301 { get; set; }
        public virtual SD_303 SD_303 { get; set; }
        public virtual SD_33 SD_33 { get; set; }
        public virtual SD_77 SD_77 { get; set; }
        public virtual SD_9 SD_9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_327> TD_327 { get; set; }
    }
}
