//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_305
    {
        public decimal DOC_CODE { get; set; }
        public decimal DOP_TYPE_DC { get; set; }
        public int TABELNUMBER { get; set; }
        public System.DateTime DOP_MONTH_BEGIN { get; set; }
        public System.DateTime DOP_MONTH_END { get; set; }
        public Nullable<double> DOP_MONTH_PERCENT { get; set; }
        public decimal DOP_LOWER_SUM { get; set; }
        public decimal DOP_UPPER_SUM { get; set; }
        public Nullable<decimal> DOP_FIX_MONTH_SUM { get; set; }
        public short DOP_TYPE { get; set; }
        public string DOP_NOTES { get; set; }
        public Nullable<decimal> DOP_CRS_DC { get; set; }
    
        public virtual SD_2 SD_2 { get; set; }
        public virtual SD_213 SD_213 { get; set; }
    }
}
