//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_310
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_310()
        {
            this.SD_61 = new HashSet<SD_61>();
        }
    
        public decimal DOC_CODE { get; set; }
        public string ILL_NAME { get; set; }
        public Nullable<int> OP_CODE { get; set; }
        public Nullable<short> NCODE { get; set; }
        public Nullable<decimal> METOD_RASCH_BOLNICH_DC { get; set; }
        public Nullable<int> OPL_1PER { get; set; }
        public Nullable<int> NEOPL_2PER { get; set; }
        public Nullable<decimal> OPL_3PER_DOLA { get; set; }
        public Nullable<short> NACHISLENIE_TYPE_CODE { get; set; }
    
        public virtual SD_307 SD_307 { get; set; }
        public virtual VD_46 VD_46 { get; set; }
        public virtual UD_197 UD_197 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_61> SD_61 { get; set; }
    }
}
