//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_302
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_302()
        {
            this.TD_302 = new HashSet<TD_302>();
            this.TD_47 = new HashSet<TD_47>();
        }
    
        public decimal DOC_CODE { get; set; }
        public int PER_NUM { get; set; }
        public System.DateTime PER_DATE { get; set; }
        public string PER_WHAT_FOR { get; set; }
        public decimal PER_SUMMA { get; set; }
        public decimal PER_BANK_DC { get; set; }
        public string PER_NOTES { get; set; }
        public Nullable<decimal> PER_ZPL_MONTH_DC { get; set; }
        public Nullable<decimal> PER_SHPZ_DC { get; set; }
        public Nullable<short> NCODE { get; set; }
        public Nullable<decimal> DBF_DC { get; set; }
        public Nullable<decimal> PER_CRS_DC { get; set; }
        public Nullable<decimal> PER_UCHET_VALUTA_DC { get; set; }
        public Nullable<double> PER_UCHET_VALUTA_RATE { get; set; }
        public Nullable<decimal> PER_SUMMA_V_UCHET_VALUTE { get; set; }
        public Nullable<decimal> PER_TABEL_DC { get; set; }
        public Nullable<decimal> PER_RUB_SUMMA { get; set; }
        public Nullable<double> PER_RUB_RATE { get; set; }
    
        public virtual SD_270 SD_270 { get; set; }
        public virtual SD_282 SD_282 { get; set; }
        public virtual SD_289 SD_289 { get; set; }
        public virtual SD_301 SD_301 { get; set; }
        public virtual SD_301 SD_3011 { get; set; }
        public virtual SD_303 SD_303 { get; set; }
        public virtual VD_46 VD_46 { get; set; }
        public virtual SD_44 SD_44 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_302> TD_302 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_47> TD_47 { get; set; }
    }
}
