//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_435
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_435()
        {
            this.BD_83 = new HashSet<BD_83>();
            this.TD_435 = new HashSet<TD_435>();
            this.UD_373 = new HashSet<UD_373>();
        }
    
        public decimal DOC_CODE { get; set; }
        public string PKCH_OUT_NUM { get; set; }
        public System.DateTime PKCH_DATE { get; set; }
        public decimal PKCH_NOMENKL_DC { get; set; }
        public Nullable<decimal> PKCH_SOSTAVITEL_DC { get; set; }
        public string CREATOR { get; set; }
        public string PARTIA_NUMBER { get; set; }
        public Nullable<decimal> PKCH_PRICE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BD_83> BD_83 { get; set; }
        public virtual SD_43 SD_43 { get; set; }
        public virtual SD_83 SD_83 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_435> TD_435 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UD_373> UD_373 { get; set; }
    }
}
