//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_50
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_50()
        {
            this.NomenklMain = new HashSet<NomenklMain>();
            this.SD_161 = new HashSet<SD_161>();
            this.SD_501 = new HashSet<SD_50>();
            this.SD_83 = new HashSet<SD_83>();
            this.VD_48 = new HashSet<VD_48>();
        }
    
        public decimal DOC_CODE { get; set; }
        public string PROD_NAME { get; set; }
        public short PROD_TYPE { get; set; }
        public string PROD_ED_IZM { get; set; }
        public Nullable<decimal> PROD_PARENT_DC { get; set; }
        public string PROD_FULL_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NomenklMain> NomenklMain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_161> SD_161 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_50> SD_501 { get; set; }
        public virtual SD_50 SD_502 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_83> SD_83 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VD_48> VD_48 { get; set; }
    }
}
