//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_83_Transfer
    {
        public System.Guid Id { get; set; }
        public System.DateTime Date { get; set; }
        public decimal SkladDC { get; set; }
        public decimal NomenklOutDC { get; set; }
        public decimal NomenklInDC { get; set; }
        public decimal Quantity { get; set; }
        public decimal PriceIn { get; set; }
        public string Creator { get; set; }
        public string Note { get; set; }
    
        public virtual SD_27 SD_27 { get; set; }
        public virtual SD_83 SD_83 { get; set; }
        public virtual SD_83 SD_831 { get; set; }
    }
}
