//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_900
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_900()
        {
            this.TD_903 = new HashSet<TD_903>();
        }
    
        public decimal DOC_CODE { get; set; }
        public string AC_NAME { get; set; }
        public int AC_TYPE { get; set; }
        public int AC_PERIOD { get; set; }
        public int AC_QUANTITY_IN_PERIOD { get; set; }
        public int AC_SUM_CONTROL { get; set; }
        public Nullable<decimal> AC_LINK_VARIABLE { get; set; }
        public Nullable<decimal> AC_LINK_PROCEDURES { get; set; }
        public string AC_NOTES { get; set; }
        public int AC_CAN_CHANGE { get; set; }
        public int AC_CODE { get; set; }
    
        public virtual SD_901 SD_901 { get; set; }
        public virtual SD_902 SD_902 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_903> TD_903 { get; set; }
    }
}
