//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHORT_NOMENKL
    {
        public decimal DOC_CODE { get; set; }
        public string NOM_NOMENKL { get; set; }
        public decimal NOM_ED_IZM_DC { get; set; }
        public string ED_IZM_NAME { get; set; }
        public string NOM_FULL_NAME { get; set; }
        public string NOM_NAME { get; set; }
        public int NOM_0MATER_1USLUGA { get; set; }
        public Nullable<decimal> NOM_SALE_CRS_DC { get; set; }
        public string CRS_NAME { get; set; }
    }
}
