//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignatureSchemes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SignatureSchemes()
        {
            this.SignatureSchemesInfo = new HashSet<SignatureSchemesInfo>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid DbId { get; set; }
        public string Name { get; set; }
        public int DocumentTYpeId { get; set; }
        public string Note { get; set; }
    
        public virtual DataSources DataSources { get; set; }
        public virtual KursMenuItem KursMenuItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SignatureSchemesInfo> SignatureSchemesInfo { get; set; }
    }
}
