//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignatureSchemesInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SignatureSchemesInfo()
        {
            this.SignatureSchemesInfo1 = new HashSet<SignatureSchemesInfo>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid SignId { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public bool IsRequired { get; set; }
        public string Note { get; set; }
        public System.Guid SchemeId { get; set; }
    
        public virtual SignatureSchemes SignatureSchemes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SignatureSchemesInfo> SignatureSchemesInfo1 { get; set; }
        public virtual SignatureSchemesInfo SignatureSchemesInfo2 { get; set; }
        public virtual SignatureType SignatureType { get; set; }
    }
}
