//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockHolders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockHolders()
        {
            this.SD_33 = new HashSet<SD_33>();
            this.SD_34 = new HashSet<SD_34>();
            this.StockHolderAccrualRows = new HashSet<StockHolderAccrualRows>();
            this.StockHolderUserRights = new HashSet<StockHolderUserRights>();
            this.TD_101 = new HashSet<TD_101>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> EmployeeDC { get; set; }
        public Nullable<decimal> KontrDC { get; set; }
        public string Note { get; set; }
        public byte[] Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_33> SD_33 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_34> SD_34 { get; set; }
        public virtual SD_43 SD_43 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockHolderAccrualRows> StockHolderAccrualRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockHolderUserRights> StockHolderUserRights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_101> TD_101 { get; set; }
    }
}
