//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_254
    {
        public decimal DOC_CODE { get; set; }
        public int CODE { get; set; }
        public System.DateTime PPT_DATE { get; set; }
        public double PPT_KOL_PLAN { get; set; }
        public double PPT_KOL_FACT { get; set; }
        public Nullable<short> PPT_FLAG_EXEC { get; set; }
    
        public virtual SD_254 SD_254 { get; set; }
    }
}
