//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_266
    {
        public int CODE { get; set; }
        public int TABELNUMBER { get; set; }
        public Nullable<short> ON_LENGTH { get; set; }
    
        public virtual SD_2 SD_2 { get; set; }
    }
}
