//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_281
    {
        public int CODE { get; set; }
        public decimal DOC_CODE { get; set; }
        public System.DateTime AVOT_DATE { get; set; }
        public string AVOT_TEXT { get; set; }
        public Nullable<decimal> AVOT_SUMMA { get; set; }
        public Nullable<int> AVOT_UDER_CODE { get; set; }
        public string AVOT_SHPZ { get; set; }
        public Nullable<decimal> AVOT_TOV_CHECK_DC { get; set; }
        public Nullable<decimal> AVOT_SHPZ_DC { get; set; }
        public Nullable<decimal> AVOT_NORM_DC { get; set; }
        public Nullable<double> AVOT_KOL { get; set; }
        public Nullable<decimal> AVOT_VAL_DC { get; set; }
        public Nullable<double> AVOT_VAL_RATE { get; set; }
        public Nullable<decimal> AVOT_SUMMA_V_UCHET_VALUTE { get; set; }
        public Nullable<double> AVOT_UCHET_VALUTA_RATE { get; set; }
        public Nullable<decimal> AVOT_UCHET_VALUTA_DC { get; set; }
        public Nullable<decimal> AVOT_KONTR_POLUCH_DC { get; set; }
        public Nullable<decimal> AVOT_KONTR_SUMMA { get; set; }
        public Nullable<decimal> AVOT_KONTR_CRS_DC { get; set; }
        public Nullable<double> AVOT_KONTR_RATE { get; set; }
        public byte[] TSTAMP { get; set; }
    
        public virtual SD_281 SD_281 { get; set; }
        public virtual SD_301 SD_301 { get; set; }
        public virtual SD_301 SD_3011 { get; set; }
        public virtual SD_301 SD_3012 { get; set; }
        public virtual SD_303 SD_303 { get; set; }
        public virtual SD_43 SD_43 { get; set; }
        public virtual SD_51 SD_51 { get; set; }
        public virtual SD_73 SD_73 { get; set; }
        public virtual TD_156 TD_156 { get; set; }
    }
}
