//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_236
    {
        public decimal DOC_CODE { get; set; }
        public int CODE { get; set; }
        public Nullable<decimal> TTNT_RASH_ORD_DC { get; set; }
        public System.DateTime TTNT_DATE { get; set; }
        public int TTNT_NUM { get; set; }
        public Nullable<decimal> TTNT_SKLAD_OTPR_DC { get; set; }
        public string TTNT_TMC_NAME { get; set; }
        public string TTNT_ED_IZM { get; set; }
        public double TTNT_KOL { get; set; }
        public Nullable<double> TTNT_VES { get; set; }
    
        public virtual SD_236 SD_236 { get; set; }
        public virtual SD_24 SD_24 { get; set; }
        public virtual SD_27 SD_27 { get; set; }
    }
}
