//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_26_CurrencyConvert
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TD_26_CurrencyConvert()
        {
            this.DistributeNakladRow = new HashSet<DistributeNakladRow>();
            this.ProjectDocuments = new HashSet<ProjectDocuments>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid NomenklId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Quantity { get; set; }
        public decimal Rate { get; set; }
        public decimal Price { get; set; }
        public decimal PriceWithNaklad { get; set; }
        public decimal Summa { get; set; }
        public decimal SummaWithNaklad { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> DOC_CODE { get; set; }
        public Nullable<int> CODE { get; set; }
        public decimal StoreDC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistributeNakladRow> DistributeNakladRow { get; set; }
        public virtual SD_27 SD_27 { get; set; }
        public virtual TD_26 TD_26 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectDocuments> ProjectDocuments { get; set; }
    }
}
