//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_301N
    {
        public string DC { get; set; }
        public string DC2 { get; set; }
        public System.DateTime CRS_DATE { get; set; }
        public Nullable<decimal> DOC_CODE { get; set; }
        public Nullable<decimal> CRS_RATE { get; set; }
        public Nullable<decimal> DOC_CODE2 { get; set; }
        public Nullable<decimal> CRS_NORM_KOEF { get; set; }
        public decimal CRS_CB_DIRECT { get; set; }
        public decimal CRS_CB_REVERSE { get; set; }
        public Nullable<decimal> CRS_INNER_DIRECT { get; set; }
        public Nullable<decimal> CRS_INNER_REVERSE { get; set; }
        public Nullable<decimal> CRS_OUTER_DIRECT { get; set; }
        public Nullable<decimal> CRS_OUTER_REVERSE { get; set; }
    }
}
