//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_436
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TD_436()
        {
            this.UD_436 = new HashSet<UD_436>();
        }
    
        public decimal DOC_CODE { get; set; }
        public int CODE { get; set; }
        public int TKPT_NOMER_PP { get; set; }
        public decimal TKPT_RAB_MESTO_DC { get; set; }
        public decimal TKPT_RAB_OPERACIA_DC { get; set; }
        public double TKPT_TIME_TRUDOEMKOST { get; set; }
        public Nullable<double> TKPT_TIME_PODGOTOVIT { get; set; }
    
        public virtual SD_247 SD_247 { get; set; }
        public virtual SD_428 SD_428 { get; set; }
        public virtual SD_436 SD_436 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UD_436> UD_436 { get; set; }
    }
}
