//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TYPES()
        {
            this.EXT_FIND = new HashSet<EXT_FIND>();
            this.EXT_FIND_MAIN = new HashSet<EXT_FIND_MAIN>();
            this.EXT_GRP = new HashSet<EXT_GRP>();
            this.EXT_PRINT2DOC = new HashSet<EXT_PRINT2DOC>();
            this.EXT_USER_OUTLINE = new HashSet<EXT_USER_OUTLINE>();
            this.TD_183 = new HashSet<TD_183>();
            this.EXT_DOC2TAB = new HashSet<EXT_DOC2TAB>();
            this.EXT_ARMS = new HashSet<EXT_ARMS>();
            this.EXT_CROSSTBL = new HashSet<EXT_CROSSTBL>();
            this.EXT_PROC = new HashSet<EXT_PROC>();
            this.EXT_USER_PROC = new HashSet<EXT_USER_PROC>();
            this.SD_303 = new HashSet<SD_303>();
        }
    
        public int TABLE_CODE { get; set; }
        public Nullable<double> TYPE_CODE { get; set; }
        public string TYPE_NAME { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<short> TYPE_CLASS { get; set; }
        public string TYPE_SALFORM { get; set; }
        public Nullable<int> PARENT_TBCODE { get; set; }
        public string PIC_NORMAL { get; set; }
        public string PIC_SELECT { get; set; }
        public Nullable<int> ACCOUNT { get; set; }
        public Nullable<short> VISIBLE { get; set; }
        public string PIC_FILE { get; set; }
        public Nullable<int> PIC_TYPE { get; set; }
        public string FORM_NAME { get; set; }
        public Nullable<int> OPEN_FIND { get; set; }
        public string FIND_PROC { get; set; }
        public Nullable<int> print_id { get; set; }
        public Nullable<int> NEW_VERSION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_FIND> EXT_FIND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_FIND_MAIN> EXT_FIND_MAIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_GRP> EXT_GRP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_PRINT2DOC> EXT_PRINT2DOC { get; set; }
        public virtual EXT_SEARCH EXT_SEARCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_USER_OUTLINE> EXT_USER_OUTLINE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_183> TD_183 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_DOC2TAB> EXT_DOC2TAB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_ARMS> EXT_ARMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_CROSSTBL> EXT_CROSSTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_PROC> EXT_PROC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXT_USER_PROC> EXT_USER_PROC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_303> SD_303 { get; set; }
    }
}
