//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UD_109
    {
        public decimal DOC_CODE { get; set; }
        public int CODE { get; set; }
        public Nullable<decimal> NARU_RAB_DC { get; set; }
        public Nullable<int> NARU_NORM_CODE { get; set; }
        public Nullable<int> NARU_ISPOL_NORM_CODE { get; set; }
        public double NARU_ZADANIE { get; set; }
        public Nullable<double> NARU_ZADANIE_CHAS { get; set; }
        public Nullable<double> NARU_ISPOLNENIE { get; set; }
        public Nullable<double> NARU_ISPOLNENIE_CHAS { get; set; }
        public Nullable<decimal> NARU_SUMMA { get; set; }
        public Nullable<double> NARU_KOEF1_POPRAV { get; set; }
        public Nullable<double> NARU_KOEF2_PEREM { get; set; }
        public Nullable<double> NARU_KOEF3_UKLADKA { get; set; }
        public Nullable<double> NARU_KOEF4_RASSTOYAN { get; set; }
        public Nullable<double> NARU_KOEF6_VREDNOST { get; set; }
        public Nullable<double> NARU_FACT_TIME { get; set; }
        public string NARU_NOTES { get; set; }
        public Nullable<double> NARU_MAX_MASSA_ONE { get; set; }
        public string NARU_ED_IZM_ZADAN { get; set; }
        public string NARU_ED_IZM_ED_GRUSA { get; set; }
    
        public virtual SD_109 SD_109 { get; set; }
        public virtual SD_249 SD_249 { get; set; }
        public virtual TD_249 TD_249 { get; set; }
        public virtual TD_249 TD_2491 { get; set; }
    }
}
