//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UD_165
    {
        public decimal DOC_CODE { get; set; }
        public int STDP_TABLE_CODE { get; set; }
    
        public virtual SD_165 SD_165 { get; set; }
    }
}
