//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_101
    {
        public decimal DOC_CODE { get; set; }
        public int CODE { get; set; }
        public string VVT_DOC_NUM { get; set; }
        public Nullable<decimal> VVT_VAL_PRIHOD { get; set; }
        public Nullable<decimal> VVT_VAL_RASHOD { get; set; }
        public Nullable<decimal> VVT_KONTRAGENT { get; set; }
        public decimal VVT_CRS_DC { get; set; }
        public Nullable<decimal> VVT_PLAT_PORUCH_DC { get; set; }
        public Nullable<short> VVT_KURS_RAZN { get; set; }
        public Nullable<decimal> VVT_RUB_PRIHOD { get; set; }
        public Nullable<decimal> VVT_RUB_RASHOD { get; set; }
        public Nullable<decimal> VVT_SHPZ_DC { get; set; }
        public Nullable<decimal> VVT_PLATEL_POLUCH_DC { get; set; }
        public Nullable<decimal> VVT_KONTR_CRS_DC { get; set; }
        public Nullable<double> VVT_KONTR_CRS_RATE { get; set; }
        public Nullable<decimal> VVT_KONTR_CRS_SUMMA { get; set; }
        public Nullable<decimal> VVT_UCHET_VALUTA_DC { get; set; }
        public Nullable<double> VVT_UCHET_VALUTA_RATE { get; set; }
        public Nullable<decimal> VVT_SUMMA_V_UCHET_VALUTE { get; set; }
        public Nullable<decimal> VVT_SFACT_POSTAV_DC { get; set; }
        public Nullable<decimal> VVT_SFACT_CLIENT_DC { get; set; }
        public Nullable<decimal> VVT_SF_OPLACHENO { get; set; }
        public Nullable<decimal> VVT_SF_CRS_DC { get; set; }
        public Nullable<double> VVT_SF_CRS_RATE { get; set; }
        public Nullable<decimal> VVT_RASH_KASS_ORDER_DC { get; set; }
        public Nullable<decimal> VVT_KASS_PRIH_ORDER_DC { get; set; }
        public Nullable<decimal> VVT_DOG_OTGR_DC { get; set; }
        public System.DateTime VV_START_DATE { get; set; }
        public System.DateTime VV_STOP_DATE { get; set; }
        public decimal VV_ACC_DC { get; set; }
        public Nullable<decimal> VV_RUB_MONEY_START { get; set; }
        public Nullable<decimal> VV_RUB_MONEY_STOP { get; set; }
    }
}
