//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_VNUTSOVM
    {
        public int UPPER_IERARHY { get; set; }
        public string WORK_NAME { get; set; }
        public int TABELNUMBER { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> CATEG_DOL { get; set; }
        public string DOL_NAME { get; set; }
        public Nullable<decimal> PERSGROUP_DC { get; set; }
        public string PG_NAME { get; set; }
    }
}
