//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vd_149
    {
        public decimal DOC_CODE { get; set; }
        public decimal PBV_SKLAD_DC { get; set; }
        public decimal PBV_NOMENKL_DC { get; set; }
        public double PBV_KOL { get; set; }
        public Nullable<decimal> PBV_UCH_SUM { get; set; }
    }
}
