//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersionInfo
    {
        public System.Guid Id { get; set; }
        public string Info { get; set; }
        public int Major { get; set; }
        public int Minor { get; set; }
        public int Version { get; set; }
    }
}
