//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WD_13
    {
        public decimal DOC_CODE { get; set; }
        public int CODE { get; set; }
        public System.DateTime MONTH { get; set; }
        public Nullable<decimal> MONTH_SUM { get; set; }
        public Nullable<double> MONTH_HOURS { get; set; }
        public Nullable<decimal> DAY_AVER { get; set; }
        public Nullable<short> RUCH_VVOD { get; set; }
        public string RUCH_VVOD_CREATOR { get; set; }
        public Nullable<System.DateTime> RUCH_VVOD_DATE { get; set; }
        public Nullable<double> PROC_INDEX { get; set; }
    
        public virtual SD_13 SD_13 { get; set; }
    }
}
