//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WD_9
    {
        public decimal DOC_CODE { get; set; }
        public int CODE { get; set; }
        public decimal ZAKW_NOMENKL_DC { get; set; }
        public double ZAKW_KOL { get; set; }
    
        public virtual SD_83 SD_83 { get; set; }
        public virtual SD_9 SD_9 { get; set; }
    }
}
