//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class XD_138
    {
        public decimal DOC_CODE { get; set; }
        public decimal BSX_NOM_DC { get; set; }
        public decimal BSX_FIRM_DC { get; set; }
        public Nullable<double> BSX_KOL { get; set; }
        public Nullable<decimal> BSX_CENA { get; set; }
    
        public virtual SD_138 SD_138 { get; set; }
        public virtual SD_83 SD_83 { get; set; }
    }
}
