//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class XD_27
    {
        public decimal DOC_CODE { get; set; }
        public decimal SKLX_RESOURCE_DC { get; set; }
        public double SKLX_KOL { get; set; }
    
        public virtual SD_27 SD_27 { get; set; }
        public virtual SD_275 SD_275 { get; set; }
    }
}
