//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class XD_203
    {
        public decimal DOC_CODE { get; set; }
        public int CODE { get; set; }
        public decimal PSX_SHPZ_DC { get; set; }
        public decimal PSX_CO_DC { get; set; }
        public decimal PSX_NOMENKL_DC { get; set; }
        public decimal PSX_DIRECT_SUM { get; set; }
        public decimal PSX_CO_SUM { get; set; }
        public decimal PSX_OH_SUM { get; set; }
        public decimal PSX_COMMON_SUM { get; set; }
    
        public virtual SD_203 SD_203 { get; set; }
        public virtual SD_303 SD_303 { get; set; }
        public virtual SD_40 SD_40 { get; set; }
        public virtual SD_83 SD_83 { get; set; }
    }
}
