using System.Windows;
using DevExpress.Data;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Grid;
using KursAM2.ViewModel.Logistiks.AktSpisaniya;

namespace KursAM2.View.Logistiks.AktSpisaniya
{
    /// <summary>
    ///     Interaction logic for AktSpisaniyaView.xaml
    /// </summary>
    public partial class AktSpisaniyaView
    {
        public AktSpisaniyaView()
        {
            InitializeComponent();
            Loaded += AktSpisaniyaView_Loaded;
        }

        private void AktSpisaniyaView_Loaded(object sender, RoutedEventArgs e)
        {
            if (DataContext is AktSpisaniyaNomenklTitleWIndowViewModel ctx)
            {
                ctx.ResetVisibleCurrency();
            }
        }

        private void GridRows_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
            if (e.Column.Name.Contains("Price") || e.Column.Name.Contains("Summa"))
                e.Column.EditSettings = new CalcEditSettings
                {
                    DisplayFormat = "n2",
                    MaskUseAsDisplayFormat = true,
                    IsTextEditable = false,
                    AllowDefaultButton = false
                };
            switch (e.Column.Name)
            {
                case "Quantity":
                    e.Column.EditSettings = new CalcEditSettings
                    {
                        DisplayFormat = "n4",
                        MaskUseAsDisplayFormat = true
                    };
                    break;
                case "Note":
                    e.Column.EditSettings = new TextEditSettings
                    {
                        AcceptsReturn = true
                    };
                    break;
            }
        }

        private void GridRows_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            gridRows.TotalSummary.Clear();
            foreach (var col in gridRows.Columns)
                if (col.FieldName == "Quantity" || col.FieldName.Contains("Price") || col.FieldName.Contains("Summa"))
                    gridRows.TotalSummary.Add(new GridSummaryItem
                    {
                        DisplayFormat = "n2",
                        SummaryType = SummaryItemType.Sum,
                        FieldName = col.FieldName,
                        ShowInColumn = col.FieldName
                    });

            gridRows.TotalSummary.Add(new GridSummaryItem
            {
                DisplayFormat = "n0",
                SummaryType = SummaryItemType.Count,
                FieldName = "Nomenkl",
                ShowInColumn = "Nomenkl"
            });
        }
    }
}