using System.Windows;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Grid;

namespace KursAM2.View.Logistiks.AktSpisaniya
{
    /// <summary>
    ///     Interaction logic for AktSpisaniyaView.xaml
    /// </summary>
    public partial class AktSpisaniyaView 
    {
        public AktSpisaniyaView()
        {
            InitializeComponent();
        }

        private void GridRows_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {

            e.Column.Name = e.Column.FieldName;
            switch (e.Column.Name)
            {
                case "Quantity":
                    e.Column.EditSettings = new CalcEditSettings
                    {
                        DisplayFormat = "n4",
                        MaskUseAsDisplayFormat = true
                    };
                    break;
                case "Price":
                case "Summa":
                    e.Column.EditSettings = new CalcEditSettings
                    {
                        DisplayFormat = "n2",
                        MaskUseAsDisplayFormat = true,
                        IsTextEditable = false,
                        AllowDefaultButton = false
                    };
                    break;
                case "Note":
                    e.Column.EditSettings = new TextEditSettings
                    {
                        AcceptsReturn = false
                    };
                    break;
            }
        }

        private void GridRows_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
        }
    }
}