using System.Windows;
using System.Windows.Input;
using DevExpress.Xpf.Grid;

namespace KursAM2.View.Logistiks.AktSpisaniya
{
    /// <summary>
    ///     Interaction logic for SelectExistNomenklOnSkladView.xaml
    /// </summary>
    public partial class SelectExistNomenklOnSkladView
    {
        public SelectExistNomenklOnSkladView()
        {
            InitializeComponent();
        }

        private void gridNomenklRows_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
            e.Column.ReadOnly = true;
            switch (e.Column.FieldName)
            {
                case "FactOtgruz":
                    e.Column.Visible = false;
                    break;
            }
        }

        private void gridNomenklRows_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
        }

        private void gridSelectNomenklRows_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
            e.Column.ReadOnly = true;
            switch (e.Column.FieldName)
            {
                case "FactOtgruz":
                    e.Column.ReadOnly = false;
                    break;
            }
        }

        private void gridSelectNomenklRows_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
        }


        private void GridNomenklRows_OnPreviewKeyDown(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.A && Keyboard.Modifiers.HasFlag(ModifierKeys.Control))  
            {  
                e.Handled = true;  
                gridNomenklRows.SelectAll();  
                gridNomenklRows.CopyToClipboard();  
            }  
        }

        private void GridSelectNomenklRows_OnPreviewKeyDown(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.A && Keyboard.Modifiers.HasFlag(ModifierKeys.Control))  
            {  
                e.Handled = true;  
                gridSelectNomenklRows.SelectAll();  
                gridSelectNomenklRows.CopyToClipboard();  
            } 
        }
    }
}
