using System.Windows;
using System.Windows.Controls;
using DevExpress.Xpf.Grid;
using KursDomain;
using LayoutManager;

namespace KursAM2.View.Management.ProfitAndLossesControls
{
    /// <summary>
    ///     Interaction logic for AccruedOfSupplierUI.xaml
    /// </summary>
    public partial class AccruedOfSupplierUI : ILayout
    {
        public AccruedOfSupplierUI()
        {
            InitializeComponent();
            LayoutManager = new LayoutManager.LayoutManager(GlobalOptions.KursSystem(),
                "KursAM2.View.Management.ProfitAndLossesControls.AccruedOfSupplierUI",
                LayoutControl);
        }

        public LayoutManager.LayoutManager LayoutManager { get; set; }
        public string LayoutManagerName { get; set; }
        public void SaveLayout()
        {
            throw new System.NotImplementedException();
        }

        private void GridRows_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
        }

        private void GridRows_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            
        }

        private void gridRows_MasterRowExpanding(object sender, RowAllowEventArgs e)
        {
            
        }

        private void AccruedGridControl_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            
        }
    }
}
