using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows;
using DevExpress.Xpf.Grid;
using KursAM2.ViewModel.Management;
using KursDomain;
using LayoutManager;

namespace KursAM2.View.Management.ProfitAndLossesControls
{
    /// <summary>
    ///     Interaction logic for ProfitAndLossExtendBaseUI.xaml
    /// </summary>
    public partial class ProfitAndLossExtendBaseUI : ILayout
    {
        public ProfitAndLossExtendBaseUI()
        {
            InitializeComponent();
            LayoutManager = new LayoutManager.LayoutManager(GlobalOptions.KursSystem(),
                "KursAM2.View.Management.ProfitAndLossesControls.ProfitAndLossExtendBaseUI",
                GridControlExtend);
            //Loaded += BalansCompareFinanseUI_Loaded;
            //Unloaded += BalansCompareFinanseUI_Unloaded;
        }

        public LayoutManager.LayoutManager LayoutManager { get; set; }
        public string LayoutManagerName { get; set; }

        public void SaveLayout()
        {
            if (DataContext is ProfitAndLossesWindowViewModel2 dtx && dtx.Extend.Count > 0 &&
                dtx.Extend.Any(_ => _.ParentId == Guid.Parse("{334973b4-1652-4473-9ded-fd4b31b31fc1}")))
                LayoutManager.Save();
        }

        private void BalansCompareFinanseUI_Unloaded(object sender, RoutedEventArgs e)
        {
            LayoutManager.Save();
        }

        private void BalansCompareFinanseUI_Loaded(object sender, RoutedEventArgs e)
        {
            LayoutManager.Load(true);
        }

        private void Grid_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
        }

        private void GridControlExtend_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            var i = 0;
            foreach (var b in GridControlExtend.Bands)
            {
                b.Name = "Band_" + i;
                i++;
            }

            if (DataContext is not ProfitAndLossesWindowViewModel2 dtx) return;
            if (dtx.ExtendActual.Count > 0)
                LayoutManager.Load(true);
            var cols = GridControlExtend.Columns
                .Where(col => col.FieldName == "AktZachetResult").ToList();
            foreach (var col in cols)
            {
               col.Visible = false;
            }
        }
    }
}
