using System.Windows;
using DevExpress.Xpf.Core;
using DevExpress.Xpf.Grid;

namespace KursAM2.View.Projects;

/// <summary>
///     Interaction logic for ProjectManager.xaml
/// </summary>
public partial class ProjectManager : ThemedWindow
{
    public ProjectManager()
    {
        InitializeComponent();
    }

    private void GridProjects_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
    {
        e.Column.Name = e.Column.FieldName;
        e.Column.ReadOnly = true;
    }

    private void GridProjects_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
    {
    }

    private void GridRows_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
    {
        e.Column.Name = e.Column.FieldName;
    }

    private void GridRows_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
    {
    }

    private void DocumentBandLeftFixedClick(object sender, RoutedEventArgs e)
    {
        var currentBand = gridDocuments.CurrentColumn?.ParentBand;
        if (currentBand == null) return;
        currentBand.Fixed = FixedStyle.Left;
    }

    private void DocumentBandRightFixedClick(object sender, RoutedEventArgs e)
    {
        var currentBand = gridDocuments.CurrentColumn?.ParentBand;
        if (currentBand == null) return;
        currentBand.Fixed = FixedStyle.Right;
    }

    private void DocumentBandNoneFixedClick(object sender, RoutedEventArgs e)
    {
        var currentBand = gridDocuments.CurrentColumn?.ParentBand;
        if (currentBand == null) return;
        currentBand.Fixed = FixedStyle.None;
    }
}
