using DevExpress.Xpf.Core;
using DevExpress.Xpf.Grid;
using KursAM2.ViewModel.Management.Projects;
using KursDomain.Documents.CommonReferences;
using KursDomain.Documents.Projects;
using System;
using System.Drawing;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using Brushes = System.Windows.Media.Brushes;

namespace KursAM2.View.Projects;

/// <summary>
///     Interaction logic for ProjectNomenklMove.xaml
/// </summary>
public partial class ProjectNomenklMove : ThemedWindow
{
    
    public ProjectNomenklMove()
    {
        InitializeComponent();
        tableViewDocumentRows.AddHandler(ScrollViewer.ScrollChangedEvent, new ScrollChangedEventHandler(this.ScrollChanged));

    }

    private void setDefaultStyleForManualColumns()
    {
        for (var i = 0; i < gridDocumentsRows.VisibleRowCount; i++)
        {
            foreach (var col in gridDocumentsRows.Columns)
            {
                var cell = tableViewDocumentRows.GetCellElementByRowHandleAndColumn(
                    i, col);
                if (cell == null) continue;
                var oldStyle = cell.Style;
                var newStyle = new Style(typeof(CellContentPresenter), oldStyle)
                {
                    TargetType = typeof(LightweightCellEditor)
                };
                newStyle.Setters.Add(
                    new Setter(LightweightCellEditor.BackgroundProperty, Brushes.Transparent));
                cell.Style = newStyle;

            }
        }
    }

    private string getManualColumnName(DocumentType type)
    {
        return type switch
        {
            DocumentType.InvoiceClient => nameof(ProjectNomenklMoveDocumentInfo.ManualClientQuantity),
            DocumentType.InvoiceProvider or DocumentType.NomenklCurrencyConverterProvider => nameof(
                ProjectNomenklMoveDocumentInfo.ManualProviderQuantity),
            _ => string.Empty
        };
    }

    private void ScrollChanged(object sender, ScrollChangedEventArgs e)
    {
        setDefaultStyleForManualColumns();
        for (var i = 0; i < gridDocumentsRows.VisibleRowCount; i++)
        {
            var row = gridDocumentsRows.GetRow(i) as ProjectNomenklMoveDocumentInfo;
            if (row == null) continue;
            var names = getManualColumnName(row.DocumentType);
            var cell = tableViewDocumentRows.GetCellElementByRowHandleAndColumn(
                i, gridDocumentsRows.Columns.FirstOrDefault(col =>
                    col.FieldName ==getManualColumnName(row.DocumentType)));
            if (cell != null) setEditStyle(cell);
        }

    }

    private static void setEditStyle(FrameworkElement cell)
    {
        if (cell != null)
        {
            var oldStyle = cell.Style;
            var newStyle = new Style(typeof(CellContentPresenter), oldStyle)
            {
                TargetType = typeof(LightweightCellEditor)
            };
            newStyle.Setters.Add(
                new Setter(FontWeightProperty, FontWeights.Black));
                
            cell.Style = newStyle;
        }
    }

    private void GridProjects_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
    {
        e.Column.Name = e.Column.FieldName;
        e.Column.ReadOnly = true;
    }

    private void GridProjects_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
    {
    }

    private void GridNomenklRows_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
    {
        e.Column.Name = e.Column.FieldName;
        e.Column.ReadOnly = true;
    }

    private void GridNomenklRows_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
    {
    }

    private void GridDocumentRows_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
    {
        e.Column.Name = e.Column.FieldName;
        e.Column.ReadOnly = true;
        switch (e.Column.FieldName)
        {
            case "IsManualChanged":
                e.Column.Visible = false;
                break;
        }
        
    }

    private void GridDocumentRows_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
    {
    }

    
    private void gridDocumentsRows_CurrentItemChanged(object sender, CurrentItemChangedEventArgs e)
    {
        if (DataContext is not ProjectNomenklMoveViewModel dtx) return;
        if (dtx.CurrentDocument != null)
        {
            foreach (var col in gridDocumentsRows.Columns)
            {
                var names = getManualColumnName(dtx.CurrentDocument.DocumentType);
                col.ReadOnly = col.FieldName != getManualColumnName(dtx.CurrentDocument.DocumentType);
            }

        }
    }
   
}
