using System.Windows;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Grid;
using KursAM2.View.Helper;
using LayoutManager;

namespace KursAM2.View.Finance.UC
{
    /// <summary>
    ///     Interaction logic for MutualAccountingDataTablesUC.xaml
    /// </summary>
    public partial class MutualAccountingDataTablesUC
    {
        public MutualAccountingDataTablesUC()
        {
            InitializeComponent();
            LayoutManagerDebitor = new LayoutManager.LayoutManager(
                "KursAM2.View.Finance.UC.MutualAccountingDataTablesUC.gridControlDebitor",
                gridControlDebitor);
            LayoutManagerCreditor = new LayoutManager.LayoutManager(
                "KursAM2.View.Finance.UC.MutualAccountingDataTablesUC.gridControlCreditor",
                gridControlCreditor);
            //LayoutManager = new LayoutManager.LayoutManager(
            //        "KursAM2.View.Finance.UC.MutualAccountingDataTablesUC",
            //    mainLayoutControl);
            //Loaded += MutualAccountingDataTablesUC_Loaded;
            //Unloaded += MutualAccountingDataTablesUC_Unloaded;
        }

        public LayoutManagerBase LayoutManagerCreditor { get; set; }
        public LayoutManagerBase LayoutManagerDebitor { get; set; }
        public LayoutManagerBase LayoutManager { get; set; }

        //private void MutualAccountingDataTablesUC_Unloaded(object sender, RoutedEventArgs e)
        //{
        //    LayoutManager.Save();
        //}

        //private void MutualAccountingDataTablesUC_Loaded(object sender, RoutedEventArgs e)
        //{
        //    //LayoutManager.Load(true);
        //}

        private void GridControlCreditor_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
        }

        private void GridControlCreditor_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            foreach (var col in gridControlCreditor.Columns)
                if (col.FieldType == typeof(decimal) || col.FieldType == typeof(decimal?))
                    col.EditSettings = new CalcEditSettings
                    {
                        AllowDefaultButton = true,
                        DisplayFormat = "n2"
                    };
            LayoutManagerCreditor.Load(true);
        }

        private void GridControlDebitor_OnAutoGeneratingColumn(object sender, AutoGeneratingColumnEventArgs e)
        {
            e.Column.Name = e.Column.FieldName;
        }

        private void GridControlDebitor_OnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            foreach (var col in gridControlDebitor.Columns)
                if (col.FieldType == typeof(decimal) || col.FieldType == typeof(decimal?))
                    col.EditSettings = new CalcEditSettings
                    {
                        AllowDefaultButton = true,
                        DisplayFormat = "n2"
                    };
            LayoutManagerDebitor.Load(true);
        }

        private void GridLayoutHelperDebitor_Trigger(object sender, MyEventArgs e)
        {
            LayoutManagerDebitor.Save();
        }

        private void GridLayoutHelperCreditor_Trigger(object sender, MyEventArgs e)
        {
            LayoutManagerCreditor.Save();
        }
    }
}